### ISSUE TITLE
unhandled exception when configuring in vscode

### ISSUE THREAD

**Issue by BarrettLowe** [microsoft/vscode-cmake-tools#1432]
### Brief Issue Summary

I am getting a warning that looks similar to other bugs but I cannot find something that directly applies. When configuring I get the following in my output window:

### Expected:

This error doesn't happen as nothing is incorrect in my CMakeLists.txt file.

### Apparent Behavior:

```
[cmake] CMake Warning at hoists/P2/bootloader/CMakeLists.txt:22 (MESSAGE):
[rollbar] Unhandled exception: Unhandled exception: Processing "data" event from proc stderr TypeError: message must be set {"data":{"type":"Buffer","data":[67,77,97,107,101,32,87,97,114,110,105,110,103,32,97,116,32,104,111,105,115,116,115,47,80,50,47,98,111,111,116,108,111,97,100,101,114,47,67,77,97,107,101,76,105,115,116,115,46,116,120,116,58,50,50,32,40,77,69,83,83,65,71,69,41,58,10,32,32,84,104,101,32,108,105,110,107,101,114,32,115,99,114,105,112,116,32,102,111,114,32,116,104,101,32,80,50,32,98,111,111,116,108,111,97,100,101,114,32,97,110,100,32,97,112,112,32,105,115,32,99,117,114,114,101,110,116,108,121,32,116,104,101,32,115,97,109,101,46,10,10,10]},"command":"C:\\Program Files\\CMake\\bin\\cmake.EXE","args":["--no-warn-unused-cli","-DCMAKE_SH=CMAKE_SH-NOTFOUND","-DPLATFORM:STRING=IMXRT1064","-DRUNNING_ON:STRING=TARGET","-DCMAKE_TRY_COMPILE_TARGET_TYPE:STRING=STATIC_LIBRARY","-DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE","-DCMAKE_BUILD_TYPE:STRING=Debug","-DCMAKE_TOOLCHAIN_FILE:FILEPATH=c:\\p4\\blowe_UTB\\iar-toolchain.cmake","-Hc:/p4/blowe_UTB","-Bc:/p4/blowe_UTB/cmakebuild/debug_iMXRT1064","-G","MinGW Makefiles"]}
[cmake] -- Configuring done
[cmake] -- Generating done
[cmake] -- Build files have been written to: C:/p4/blowe_UTB/cmakebuild/debug_iMXRT1064
[cmake] CMake Warning at hoists/P2/bootloader/CMakeLists.txt:22 (MESSAGE):
[rollbar] Unhandled exception: Unhandled exception: Resolving process on "close" event TypeError: message must be set {"line_acc":"","stderr_line_acc":"CMake Warning at hoists/P2/bootloader/CMakeLists.txt:22 (MESSAGE):","command":"C:\\Program Files\\CMake\\bin\\cmake.EXE","retc":0}
[cmakefileapi-parser] Read reply folder: c:\p4\blowe_UTB\cmakebuild\debug_iMXRT1064\.cmake\api\v1\reply
[cmakefileapi-parser] Found index files: ["cache-v2-08e4701c3a9ad200fc89.json","codemodel-v2-122912f7e55a273442c5.json","index-2020-09-11T18-31-25-0784.json","target-EtcPal-Debug-416c1bdae9b6dfd3f339.json","target-FreeRTOS-Debug-3a3aa4e0a2bdab080277.json","target-HAL-Debug-8d3b26e2028198fec136.json","target-HoistLib-Debug-8b8c7036a32fb8914f33.json","target-HoistMiddlewareLib-Debug-2c587eeb5dffc4c2dd52.json","target-MCXHoistLib-Debug-f30c1032de898ef9dbd7.json","target-P2AppTestable-Debug-7fa65b5ee6df8150f594.json","target-P2UnityTest-Debug-f11fa9ae584348e6510e.json","target-P2UpThereBox-Debug-f45874547a2a7d5bdae4.json","target-P2_Bootloader-Debug-ed9a0e690da04d58ff2c.json","target-P2_BootloaderTestable-Debug-1a5ac748ebac7729f1e4.json","target-RigCommon-Debug-627a407c0e405cdf1b92.json","target-RiggingPAL-Debug-44f6e7bf98abd6a212cd.json","target-SDK_IMXRT1064-Debug-fc3e80d7f55d1cd1caf6.json"]
[cache] Reading CMake cache file c:/p4/blowe_UTB/cmakebuild/debug_iMXRT1064/CMakeCache.txt
[cache] Parsing CMake cache string
```
However if I look at the line where the error occurred, it looks completely legitimate:
`MESSAGE(WARNING "Warning of some sort")`

If I run the same cmake command in a prompt outside vscode, no error occurs.

### CMake Tools Log

```
*** Not sure where to find this ***
```

### Developer Tools Log

```﻿
mainThreadExtensionService.ts:66 TypeError: message must be set
	at new V (c:\Users\blowe\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:508:651)
	at new V (c:\Users\blowe\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:497:187)
	at CMakeOutputConsumer._parseDiags (c:\Users\blowe\.vscode\extensions\ms-vscode.cmake-tools-1.4.1\dist\main.js:17318:36)
	at CMakeOutputConsumer.error (c:\Users\blowe\.vscode\extensions\ms-vscode.cmake-tools-1.4.1\dist\main.js:17298:14)
	at c:\Users\blowe\.vscode\extensions\ms-vscode.cmake-tools-1.4.1\dist\main.js:2775:48
	at RollbarController.invoke (c:\Users\blowe\.vscode\extensions\ms-vscode.cmake-tools-1.4.1\dist\main.js:1351:20)
	at Socket.<anonymous> (c:\Users\blowe\.vscode\extensions\ms-vscode.cmake-tools-1.4.1\dist\main.js:2769:39)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
console.ts:137 [Extension Host] [CMakeTools] 2020-09-11T18:46:10.432Z [info] [cmake] -- Configuring done
console.ts:137 [Extension Host] [CMakeTools] 2020-09-11T18:46:11.497Z [info] [cmake] -- Generating done
console.ts:137 [Extension Host] [CMakeTools] 2020-09-11T18:46:11.608Z [info] [cmake] -- Build files have been written to: C:/p4/blowe_UTB/cmakebuild/debug_iMXRT1064
console.ts:137 [Extension Host] [CMakeTools] 2020-09-11T18:46:11.618Z [error] [cmake] CMake Warning at hoists/P2/bootloader/CMakeLists.txt:22 (MESSAGE):
console.ts:137 [Extension Host] [CMakeTools] 2020-09-11T18:46:11.618Z [fatal] [rollbar] Unhandled exception: Unhandled exception: Resolving process on "close" event TypeError: message must be set {"line_acc":"","stderr_line_acc":"CMake Warning at hoists/P2/bootloader/CMakeLists.txt:22 (MESSAGE):","command":"C:\\Program Files\\CMake\\bin\\cmake.EXE","retc":0}
console.ts:137 [Extension Host] TypeError: message must be set
	at new V (c:\Users\blowe\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:508:651)
	at new V (c:\Users\blowe\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:497:187)
	at CMakeOutputConsumer._parseDiags (c:\Users\blowe\.vscode\extensions\ms-vscode.cmake-tools-1.4.1\dist\main.js:17318:36)
	at CMakeOutputConsumer.error (c:\Users\blowe\.vscode\extensions\ms-vscode.cmake-tools-1.4.1\dist\main.js:17298:14)
	at c:\Users\blowe\.vscode\extensions\ms-vscode.cmake-tools-1.4.1\dist\main.js:2795:48
	at RollbarController.invoke (c:\Users\blowe\.vscode\extensions\ms-vscode.cmake-tools-1.4.1\dist\main.js:1351:20)
	at ChildProcess.<anonymous> (c:\Users\blowe\.vscode\extensions\ms-vscode.cmake-tools-1.4.1\dist\main.js:2790:43)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
console.ts:137 [Extension Host] [CMakeTools] 2020-09-11T18:46:11.619Z [debug] [cmakefileapi-parser] Read reply folder: c:\p4\blowe_UTB\cmakebuild\debug_iMXRT1064\.cmake\api\v1\reply
console.ts:137 [Extension Host] [CMakeTools] 2020-09-11T18:46:11.620Z [debug] [cmakefileapi-parser] Found index files: ["cache-v2-08e4701c3a9ad200fc89.json","codemodel-v2-e4ab333cc093d8c2c718.json","index-2020-09-11T18-46-11-0604.json","target-EtcPal-Debug-416c1bdae9b6dfd3f339.json","target-FreeRTOS-Debug-3a3aa4e0a2bdab080277.json","target-HAL-Debug-8d3b26e2028198fec136.json","target-HoistLib-Debug-8534fc607f29ed4f6751.json","target-HoistMiddlewareLib-Debug-a42c2fcbeeb2d7f82d3a.json","target-MCXHoistLib-Debug-87789c506f72dd572eb0.json","target-P2AppTestable-Debug-038da44ed27eb5bdd840.json","target-P2UnityTest-Debug-8d989cfdf1a24b87aa04.json","target-P2UpThereBox-Debug-1184a2b315bb06095e66.json","target-P2_Bootloader-Debug-f047908e61fd8176a47f.json","target-P2_BootloaderTestable-Debug-70a52bbf398ab3e1a9b3.json","target-RigCommon-Debug-37269f56a015bb17c7d2.json","target-RiggingPAL-Debug-44f6e7bf98abd6a212cd.json","target-SDK_IMXRT1064-Debug-fc3e80d7f55d1cd1caf6.json"]
console.ts:137 [Extension Host] [CMakeTools] 2020-09-11T18:46:11.702Z [debug] [cache] Reading CMake cache file c:/p4/blowe_UTB/cmakebuild/debug_iMXRT1064/CMakeCache.txt
console.ts:137 [Extension Host] [CMakeTools] 2020-09-11T18:46:11.707Z [debug] [cache] Parsing CMake cache string
console.ts:137 [Extension Host] [CMakeTools] 2020-09-11T18:46:11.827Z [debug] [extension] [9612] cmake.cleanConfigure finished (returned 0)
console.ts:137 [Extension Host] provideCustomConfiguration
﻿
​
```

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**: 3.16.2
- **VSCode Version**: 1.49.0
- **CMake Tools Extension Version**: 1.4.1 
- **Compiler/Toolchain**:  IAR

**Comment by xisui-MSFT** [comment]
#1433

**Comment by bigstream-valentyn** [comment]
Is there workaround for this?

**Comment by bobbrow** [comment]
@bigstream-valentyn no (unless you edit the extension sources directly), but we're releasing an update with a fix today.  Version 1.4.2.

**Comment by bobbrow** [comment]
[1.4.2](https://github.com/microsoft/vscode-cmake-tools/releases/tag/1.4.2) is now available.
