### ISSUE TITLE
Failed to load cmake tools, cannot find module 'vscode-nls'

### ISSUE THREAD

**Issue by coslyk** [microsoft/vscode-cmake-tools#1505]
### Brief Issue Summary

CMake Tools fail to start.

### Expected:

1. Open a CMake project

### Apparent Behavior:

1. Cannot run CMake Configure, no Intellisense...

### CMake Tools Log

```
[2020-10-22 22:39:48.046] [exthost] [error] Activating extension ms-vscode.cmake-tools failed due to an error:
[2020-10-22 22:39:48.103] [exthost] [error] Error: Cannot find module 'vscode-nls'
Require stack:
- /home/liuyikun/.vscode-oss/extensions/ms-vscode.cmake-tools-1.4.2/dist/main.js
- /usr/share/codium/resources/app/out/vs/loader.js
- /usr/share/codium/resources/app/out/bootstrap-amd.js
- /usr/share/codium/resources/app/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
	at Module._load (internal/modules/cjs/loader.js:690:27)
	at Function.Module._load (electron/js2c/asar.js:769:28)
	at Function.t._load (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1057:776)
	at Function.i._load (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1027:486)
	at Function.n._load (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1023:767)
	at Module.require (internal/modules/cjs/loader.js:852:19)
	at r (/usr/share/codium/resources/app/out/vs/loader.js:17:346)
	at Object.<anonymous> (/home/liuyikun/.vscode-oss/extensions/ms-vscode.cmake-tools-1.4.2/dist/main.js:671:18)
	at __webpack_require__ (/home/liuyikun/.vscode-oss/extensions/ms-vscode.cmake-tools-1.4.2/dist/main.js:21:30)
	at Object.<anonymous> (/home/liuyikun/.vscode-oss/extensions/ms-vscode.cmake-tools-1.4.2/dist/main.js:4384:13)
	at __webpack_require__ (/home/liuyikun/.vscode-oss/extensions/ms-vscode.cmake-tools-1.4.2/dist/main.js:21:30)
	at /home/liuyikun/.vscode-oss/extensions/ms-vscode.cmake-tools-1.4.2/dist/main.js:85:18
	at Object.<anonymous> (/home/liuyikun/.vscode-oss/extensions/ms-vscode.cmake-tools-1.4.2/dist/main.js:88:10)
	at Module.i._compile (/usr/share/codium/resources/app/out/vs/loader.js:17:571)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
	at Module.load (internal/modules/cjs/loader.js:815:32)
	at Module._load (internal/modules/cjs/loader.js:727:14)
	at Function.Module._load (electron/js2c/asar.js:769:28)
	at Function.t._load (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1057:776)
	at Function.i._load (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1027:486)
	at Function.n._load (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1023:767)
	at Module.require (internal/modules/cjs/loader.js:852:19)
	at require (internal/modules/cjs/helpers.js:74:18)
	at Function.s [as __$__nodeRequire] (/usr/share/codium/resources/app/out/vs/loader.js:34:963)
	at p._loadCommonJSModule (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1028:771)
	at p._doActivateExtension (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:925:742)
	at p._activateExtension (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:924:822)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Promise.all (index 0)
	at async Promise.all (index 83)
	at async Promise.all (index 1)
```

### Platform and Versions

- **Operating System**: Debian 10
- **CMake Version**: 3.13.4
- **VSCode Version**: VSCodium 1.50.1
- **CMake Tools Extension Version**: 1.4.2
- **Compiler/Toolchain**: gcc (Debian 8.3.0-6) 8.3.0

**Comment by bobbrow** [comment]
Are you able to get it working by installing version 1.4.1?  In the extensions panel, click on the gear icon for CMake Tools and pick "Install another version"

![image](https://user-images.githubusercontent.com/12818240/96942921-5db3b480-148b-11eb-8945-5af872cfdbad.png)

We'll need to investigate how that error is possible, but this should hopefully unblock you for now.

**Comment by coslyk** [comment]
@bobbrow The old version works.

**Comment by andreeis** [comment]
@coslyk, since we can't reproduce this problem, can you try any recent vsix that this repo is building now for each merged PR?
Go to "Actions" --> "Build VSIX" workflow --> pick any recent commit --> download the vsix from the link in the artifacts section.

**Comment by coslyk** [comment]
I reinstalled the latest version and now it works. Maybe there are some problems during the installation.
