### ISSUE TITLE
In my CI, it's report  [vscode-cpptools-api] C/C++ extension is not installed

### ISSUE THREAD

**Issue by lygstate** [microsoft/vscode-cmake-tools#1681]
Looking at https://github.com/lygstate/vscode-cmake-tools/runs/1936271265
How to force install C/C++ extension in CI?

**Comment by bobbrow** [comment]
CI shouldn't need the C/C++ extension.  There does seem to be a problem with `cleanString` in `rollbar.ts` though.  It should check to make sure `message` is defined before doing any processing with it.  Either way, that's strange because `exception.message` should not be undefined.

The real problem with CI on that change is related to these failures (though it may be that undefined exception message causing it and I'd be curious to know which exception this is):
```
1) Build
       ConfigureAll:
     Error: Running the contributed command: 'cmake.configureAll' failed.
      at b._executeContributedCommand (.vscode-test/vscode-1.53.2/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:88571)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at Context.<anonymous> (test/extension-tests/multi-root-UI/test/configure-and-build.test.ts:90:12)

2) ...
```
