### ISSUE TITLE
Error: Unknown diagnostic severity level with -fopt-info-vec/-O3 and GCC 10.2

### ISSUE THREAD

**Issue by fvanmaele** [microsoft/vscode-cmake-tools#1796]
### Brief Issue Summary

When using `-fopt-info-vec` to output diagnostics on vectorization with GCC 10.2, `cmake` configure or build steps result in an error after their completion:
```
​ [Extension Host] [CMakeTools] 2021-04-21T21:08:16.916Z [fatal] [rollbar] Unhandled exception: Unhandled Promise rejection: launchTarget Error: Unknown diagnostic severity level: optimized {}
```
The issue is not present with the clang11 kit.

### Expected:

1. Write a loop which can be (auto-)vectorized by GCC, for example
```
#include <vector>

double sum = 0;
int main() {
  std::vector<float> v(50000, 1.0);
  for (size_t i = 0; i < v.size(); ++i)
    sum += v[i];
}
```
2. Add `-fopt-info-vec` to compilation options:
```
add_compile_options(-fopt-info-vec)
```
3. Select GCC 10.2 as kit.
4. Select `Release` as build variant or add `-O3` to compilation options.
4. Perform `CMake: Build Target`.

### Apparent Behavior:

1. The build step completes successfully, but an error from the extension is shown.
2. `Launch the selected target in the terminal window` does not launch the target as a result.

### CMake Tools Log

```
[main] Building folder: hasc-code daxpy_bm
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /mnt/c/Users/Ferdinand/source/repos/hasc-code/build --config Release --target daxpy_bm -j 10 --
[build] [1/2  50% :: 1.498] Building CXX object CMakeFiles/daxpy_bm.dir/daxpy_bm.cc.o
[build] ../daxpy_bm.cc:30:39: optimized: loop vectorized using 32 byte vectors
[build] ../daxpy_bm.cc:30:39: optimized:  loop versioned for vectorization because of possible aliasing
[build] ../daxpy_bm.cc:30:39: optimized: loop vectorized using 16 byte vectors
[build] ../daxpy_bm.cc:37:28: optimized: loop vectorized using 32 byte vectors
[build] ../daxpy_bm.cc:37:28: optimized: loop vectorized using 16 byte vectors
[build] ../daxpy_bm.cc:37:28: optimized: loop vectorized using 32 byte vectors
[build] ../daxpy_bm.cc:37:28: optimized: loop vectorized using 16 byte vectors
[build] /usr/include/c++/10/bits/stl_numeric.h:97:22: optimized: loop vectorized using 32 byte vectors
[build] /usr/include/c++/10/bits/stl_numeric.h:97:22: optimized: loop vectorized using 16 byte vectors
[build] ../daxpy_bm.cc:37:28: optimized: loop vectorized using 32 byte vectors
[build] ../daxpy_bm.cc:37:28: optimized:  loop versioned for vectorization because of possible aliasing
[build] ../daxpy_bm.cc:37:28: optimized: loop vectorized using 16 byte vectors
[build] /usr/include/c++/10/bits/vector.tcc:505:5: optimized: basic block part vectorized using 32 byte vectors
[build] /usr/include/c++/10/bits/stl_numeric.h:97:22: optimized: loop vectorized using 32 byte vectors
[build] /usr/include/c++/10/bits/stl_numeric.h:97:22: optimized: loop vectorized using 16 byte vectors
[build] /usr/include/c++/10/bits/stl_vector.h:346:18: optimized: basic block part vectorized using 32 byte vectors
[build] /usr/include/c++/10/bits/stl_algobase.h:872:22: optimized: basic block part vectorized using 32 byte vectors
[build] /usr/include/c++/10/bits/stl_vector.h:346:18: optimized: basic block part vectorized using 32 byte vectors
[build] /usr/include/c++/10/bits/stl_algobase.h:872:22: optimized: basic block part vectorized using 32 byte vectors
[build] /usr/include/c++/10/bits/vector.tcc:69:7: optimized: basic block part vectorized using 32 byte vectors
[build] /usr/include/c++/10/bits/stl_vector.h:98:47: optimized: basic block part vectorized using 32 byte vectors
[build] ../daxpy_bm.cc:63:33: optimized: basic block part vectorized using 32 byte vectors
[build] /usr/include/c++/10/thread:149:17: optimized: basic block part vectorized using 32 byte vectors
[build] [2/2 100% :: 2.010] Linking CXX executable daxpy_bm
[build] Build finished with exit code 0
[rollbar] Unhandled exception: Unhandled Promise rejection: buildWithTarget Error: Unknown diagnostic severity level: optimized {}
```

### Developer Tools Log

```
 [Extension Host] [CMakeTools] 2021-04-21T21:10:44.038Z [debug] [extension] [8068] cmake.build started
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:44.039Z [info] [main] Building folder: hasc-code 
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:44.054Z [debug] [main] Saving open files before configure/build
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:44.091Z [info] [build] Starting build
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:44.121Z [debug] [driver] Start build all
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:44.123Z [info] [proc] Executing command: /usr/bin/cmake --build /mnt/c/Users/Ferdinand/source/repos/hasc-code/build --config Release --target all -j 10 --
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.206Z [info] [build] [5/10  10% :: 2.028] Building CXX object CMakeFiles/compiler_flags.dir/compiler_flags.cc.o
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.207Z [info] [build] /usr/include/c++/10/bits/random.tcc:409:42: optimized: loop vectorized using 16 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.207Z [info] [build] /usr/include/c++/10/bits/random.tcc:401:32: optimized: loop vectorized using 16 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.207Z [info] [build] ../compiler_flags.cc:46:30: optimized: loop vectorized using 32 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.208Z [info] [build] ../compiler_flags.cc:32:25: optimized: loop vectorized using 32 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.208Z [info] [build] ../compiler_flags.cc:32:25: optimized: loop vectorized using 16 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.402Z [info] [build] [6/10  20% :: 2.224] Building CXX object CMakeFiles/daxpy_bm.dir/daxpy_bm.cc.o
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.402Z [info] [build] ../daxpy_bm.cc:30:39: optimized: loop vectorized using 32 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.403Z [info] [build] ../daxpy_bm.cc:30:39: optimized:  loop versioned for vectorization because of possible aliasing
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.403Z [info] [build] ../daxpy_bm.cc:30:39: optimized: loop vectorized using 16 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.403Z [info] [build] ../daxpy_bm.cc:37:28: optimized: loop vectorized using 32 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.404Z [info] [build] ../daxpy_bm.cc:37:28: optimized: loop vectorized using 16 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.404Z [info] [build] ../daxpy_bm.cc:37:28: optimized: loop vectorized using 32 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.404Z [info] [build] ../daxpy_bm.cc:37:28: optimized: loop vectorized using 16 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.404Z [info] [build] /usr/include/c++/10/bits/stl_numeric.h:97:22: optimized: loop vectorized using 32 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.405Z [info] [build] /usr/include/c++/10/bits/stl_numeric.h:97:22: optimized: loop vectorized using 16 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.405Z [info] [build] ../daxpy_bm.cc:37:28: optimized: loop vectorized using 32 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.405Z [info] [build] ../daxpy_bm.cc:37:28: optimized:  loop versioned for vectorization because of possible aliasing
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.405Z [info] [build] ../daxpy_bm.cc:37:28: optimized: loop vectorized using 16 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.406Z [info] [build] /usr/include/c++/10/bits/vector.tcc:505:5: optimized: basic block part vectorized using 32 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.407Z [info] [build] /usr/include/c++/10/bits/stl_numeric.h:97:22: optimized: loop vectorized using 32 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.407Z [info] [build] /usr/include/c++/10/bits/stl_numeric.h:97:22: optimized: loop vectorized using 16 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.408Z [info] [build] /usr/include/c++/10/bits/stl_vector.h:346:18: optimized: basic block part vectorized using 32 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.408Z [info] [build] /usr/include/c++/10/bits/stl_algobase.h:872:22: optimized: basic block part vectorized using 32 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.408Z [info] [build] /usr/include/c++/10/bits/stl_vector.h:346:18: optimized: basic block part vectorized using 32 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.409Z [info] [build] /usr/include/c++/10/bits/stl_algobase.h:872:22: optimized: basic block part vectorized using 32 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.409Z [info] [build] /usr/include/c++/10/bits/vector.tcc:69:7: optimized: basic block part vectorized using 32 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.409Z [info] [build] /usr/include/c++/10/bits/stl_vector.h:98:47: optimized: basic block part vectorized using 32 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.410Z [info] [build] ../daxpy_bm.cc:63:33: optimized: basic block part vectorized using 32 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.410Z [info] [build] /usr/include/c++/10/thread:149:17: optimized: basic block part vectorized using 32 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.435Z [info] [build] [7/10  30% :: 2.256] Building CXX object CMakeFiles/daxpy.dir/daxpy.cc.o
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.435Z [info] [build] ../daxpy.cc:38:39: optimized: loop vectorized using 32 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.435Z [info] [build] ../daxpy.cc:38:39: optimized:  loop versioned for vectorization because of possible aliasing
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.436Z [info] [build] ../daxpy.cc:38:39: optimized: loop vectorized using 16 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.436Z [info] [build] ../daxpy.cc:18:26: optimized: loop vectorized using 32 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.437Z [info] [build] ../daxpy.cc:18:26: optimized:  loop versioned for vectorization because of possible aliasing
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.437Z [info] [build] ../daxpy.cc:18:26: optimized: loop vectorized using 16 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.437Z [info] [build] /usr/include/c++/10/bits/vector.tcc:505:5: optimized: basic block part vectorized using 32 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.437Z [info] [build] ../daxpy.cc:38:39: optimized: loop vectorized using 32 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.439Z [info] [build] ../daxpy.cc:38:39: optimized:  loop versioned for vectorization because of possible aliasing
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.439Z [info] [build] ../daxpy.cc:38:39: optimized: loop vectorized using 16 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.439Z [info] [build] /usr/include/c++/10/bits/stl_numeric.h:97:22: optimized: loop vectorized using 32 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.440Z [info] [build] /usr/include/c++/10/bits/stl_numeric.h:97:22: optimized: loop vectorized using 16 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.440Z [info] [build] ../daxpy.cc:84:67: optimized: basic block part vectorized using 32 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.440Z [info] [build] /usr/include/c++/10/ext/new_allocator.h:115:41: optimized: basic block part vectorized using 32 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.440Z [info] [build] /usr/include/c++/10/bits/stl_algobase.h:873:11: optimized: basic block part vectorized using 32 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.441Z [info] [build] /usr/include/c++/10/bits/vector.tcc:69:7: optimized: basic block part vectorized using 32 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.441Z [info] [build] ../daxpy.cc:60:33: optimized: basic block part vectorized using 32 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.441Z [info] [build] /usr/include/c++/10/ext/new_allocator.h:115:41: optimized: basic block part vectorized using 32 byte vectors
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.528Z [info] [build] [8/10  40% :: 2.350] Linking CXX executable compiler_flags
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.625Z [info] [build] [8/10  50% :: 2.447] Building CXX object CMakeFiles/compiler_flags_bm.dir/compiler_flags_bm.cc.o
​ [Extension Host] [CMakeTools] 2021-04-21T21:10:46.626Z [info] [build] ../compiler_flags_bm.cc:49:30: optimized: loop vectorized using 32 byte vectors
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.626Z [info] [build] /usr/include/c++/10/bits/random.tcc:409:42: optimized: loop vectorized using 16 byte vectors
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.626Z [info] [build] /usr/include/c++/10/bits/random.tcc:401:32: optimized: loop vectorized using 16 byte vectors
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.627Z [info] [build] ../compiler_flags_bm.cc:35:25: optimized: loop vectorized using 32 byte vectors
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.627Z [info] [build] ../compiler_flags_bm.cc:35:25: optimized: loop vectorized using 16 byte vectors
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.722Z [info] [build] [9/10  60% :: 2.543] Building CXX object CMakeFiles/daxpy_bm_2.dir/daxpy_bm_2.cc.o
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.722Z [info] [build] ../daxpy_bm_2.cc: In function ‘void BM_daxpy_seq(benchmark::State&)’:
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.723Z [info] [build] ../daxpy_bm_2.cc:86:9: warning: unused variable ‘nproc’ [-Wunused-variable]
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.723Z [info] [build]    86 |     int nproc = std::thread::hardware_concurrency();
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.723Z [info] [build]       |         ^~~~~
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.723Z [info] [build] ../daxpy_bm_2.cc:43:39: optimized: loop vectorized using 32 byte vectors
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.723Z [info] [build] ../daxpy_bm_2.cc:43:39: optimized:  loop versioned for vectorization because of possible aliasing
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.723Z [info] [build] ../daxpy_bm_2.cc:43:39: optimized: loop vectorized using 16 byte vectors
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.723Z [info] [build] ../daxpy_bm_2.cc:77:28: optimized: loop vectorized using 32 byte vectors
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.724Z [info] [build] ../daxpy_bm_2.cc:77:28: optimized:  loop versioned for vectorization because of possible aliasing
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.724Z [info] [build] ../daxpy_bm_2.cc:77:28: optimized: loop vectorized using 16 byte vectors
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.724Z [info] [build] /usr/include/c++/10/bits/vector.tcc:505:5: optimized: basic block part vectorized using 32 byte vectors
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.724Z [info] [build] /usr/include/c++/10/bits/random.tcc:409:42: optimized: loop vectorized using 16 byte vectors
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.724Z [info] [build] /usr/include/c++/10/bits/random.tcc:401:32: optimized: loop vectorized using 16 byte vectors
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.724Z [info] [build] ../daxpy_bm_2.cc:77:28: optimized: loop vectorized using 32 byte vectors
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.724Z [info] [build] ../daxpy_bm_2.cc:77:28: optimized:  loop versioned for vectorization because of possible aliasing
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.725Z [info] [build] ../daxpy_bm_2.cc:77:28: optimized: loop vectorized using 16 byte vectors
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.725Z [info] [build] /usr/include/c++/10/bits/stl_vector.h:346:18: optimized: basic block part vectorized using 32 byte vectors
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.725Z [info] [build] /usr/include/c++/10/bits/stl_algobase.h:872:22: optimized: basic block part vectorized using 32 byte vectors
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.725Z [info] [build] /usr/include/c++/10/bits/stl_algobase.h:872:22: optimized: basic block part vectorized using 32 byte vectors
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.725Z [info] [build] /usr/include/c++/10/ext/new_allocator.h:115:41: optimized: basic block part vectorized using 32 byte vectors
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.725Z [info] [build] /usr/include/c++/10/bits/stl_vector.h:346:18: optimized: basic block part vectorized using 32 byte vectors
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.726Z [info] [build] /usr/include/c++/10/bits/stl_algobase.h:872:22: optimized: basic block part vectorized using 32 byte vectors
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.726Z [info] [build] /usr/include/c++/10/bits/stl_algobase.h:872:22: optimized: basic block part vectorized using 32 byte vectors
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.726Z [info] [build] ../daxpy_bm_2.cc:62:33: optimized: basic block part vectorized using 32 byte vectors
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.727Z [info] [build] /usr/include/c++/10/thread:149:17: optimized: basic block part vectorized using 32 byte vectors
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.727Z [info] [build] /usr/include/c++/10/ext/new_allocator.h:115:41: optimized: basic block part vectorized using 32 byte vectors
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:46.968Z [info] [build] [10/10  70% :: 2.790] Linking CXX executable daxpy
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:47.096Z [info] [build] [10/10  80% :: 2.918] Linking CXX executable daxpy_bm
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:47.240Z [info] [build] [10/10  90% :: 3.061] Linking CXX executable compiler_flags_bm
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:47.310Z [info] [build] [10/10 100% :: 3.132] Linking CXX executable daxpy_bm_2
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:47.313Z [debug] [cmakefileapi-parser] Read reply folder: /mnt/c/Users/Ferdinand/source/repos/hasc-code/build/.cmake/api/v1/reply
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:47.321Z [debug] [cmakefileapi-parser] Found index files: ["cache-v2-09c266f70e2b00e82cae.json","codemodel-v2-912cf0c6409fc2694e7e.json","index-2021-04-21T21-10-30-0994.json","target-compiler_flags-Release-31ec964d7ccf67217c22.json","target-compiler_flags_bm-Release-f35fce08d60a1cffdd78.json","target-daxpy-Release-d3fc8b56413dedd3642a.json","target-daxpy_bm-Release-ed84d16c60054f0b734c.json","target-daxpy_bm_2-Release-baa3c62a6dc030dfb48c.json","toolchains-v1-eb2ed7562f5472d9322d.json"]
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:47.380Z [debug] [driver] Run _refreshExpansions
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:47.380Z [debug] [driver] Run _refreshExpansions cb
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:47.402Z [info] [build] Build finished with exit code 0
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:47.406Z [debug] [cache] Reading CMake cache file /mnt/c/Users/Ferdinand/source/repos/hasc-code/build/CMakeCache.txt
console.ts:137 [Extension Host] [CMakeTools] 2021-04-21T21:10:47.408Z [fatal] [rollbar] Unhandled exception: Unhandled Promise rejection: build Error: Unknown diagnostic severity level: optimized {}
m @ console.ts:137
console.ts:137 [Extension Host] Error: Unknown diagnostic severity level: optimized	at severity_of (/home/fvanmaele/.vscode-server/extensions/ms-vscode.cmake-tools-1.7.0/dist/main.js:42823:19)	at /home/fvanmaele/.vscode-server/extensions/ms-vscode.cmake-tools-1.7.0/dist/main.js:42835:89	at Array.map (<anonymous>)	at /home/fvanmaele/.vscode-server/extensions/ms-vscode.cmake-tools-1.7.0/dist/main.js:42833:26	at Array.map (<anonymous>)	at CompileOutputConsumer.resolveDiagnostics (/home/fvanmaele/.vscode-server/extensions/ms-vscode.cmake-tools-1.7.0/dist/main.js:42832:50)	at /home/fvanmaele/.vscode-server/extensions/ms-vscode.cmake-tools-1.7.0/dist/main.js:40510:61
m @ console.ts:137
notificationsAlerts.ts:40 Running the contributed command: 'cmake.build' failed.
onDidChangeNotification @ notificationsAlerts.ts:40
```

### Platform and Versions

- **Operating System**: WSL2 (Ubuntu 20.04) on Windows 10 20H2
- **CMake Version**: 3.20.1
- **VSCode Version**: 1.55.2
- **CMake Tools Extension Version**: 1.7.0
- **Compiler/Toolchain**: GCC 10.2

### Other Notes/Information

As mentioned above, this issue seems limited to GCC 10.2 and `-fopt-vec-info` is a GCC-specific option.

**Comment by andreeis** [comment]
Thank you for opening this report. Before we have a chance to actually run these repro steps, can you clarify, the configure and build operations (without invoking any launch of any target yet) succeed or fail?
If configure or build fails, does it happen when you manage your project from the terminal as well or only from VSCode? Trying to determine if the problem is with the CMake Tools extension or with CMake itself.
If configure/build succeeds, then clearly there's an extension issue when we try to launch the target and we'll look at that.

**Comment by fvanmaele** [comment]
The actual cmake invocation finishes without error in both configure and 
build step, be it in the terminal or in VSCode. When running the build 
step in VSCode however, there is an error from the extension after the 
build completes.

Following the developer console, this is apparently in the following 
code path (main.js):

```
     resolveDiagnostics(basePath) {
         const diags_by_file = new Map();
         const severity_of = (p) => {
             switch (p) {
                 case 'warning':
                     return vscode.DiagnosticSeverity.Warning;
                 case 'catastrophic error':
                 case 'fatal error':
                 case 'error':
                     return vscode.DiagnosticSeverity.Error;
                 case 'note':
                 case 'info':
                 case 'remark':
                     return vscode.DiagnosticSeverity.Information;
             }
             throw new Error('Unknown diagnostic severity level: ' + p);
         };
```

The GCC vectorizer messages are prefixed with "optimized", which is 
apparently not a case in the above switch statement, resulting in the error.
