### ISSUE TITLE
CMake: Quick Start. Unhandled Promise rejection: quickStart TypeError: Cannot read property 'value' of null {}

### ISSUE THREAD

**Issue by e1kable** [microsoft/vscode-cmake-tools#1912]
Hi, I'm new to vscode and cmake tools, so here's my issue right from the start:

### Brief Issue Summary
When trying to generate a project configuration with CMake: Quick start, I get an error right after cmake tools checks the compiler version

### CMake Tools Log

```
[proc] Executing command: "C:\Program Files\LLVM\bin\clang.exe" -v
[rollbar] Unhandled exception: Unhandled Promise rejection: quickStart TypeError: Cannot read property 'value' of null {}
```

### Developer Tools Log

```
TypeError: Cannot read property 'value' of null    
at CMakeFileApiDriver.getGeneratorFromCache (c:\Users\[...]\.vscode\extensions\ms-vscode.cmake-tools-1.7.3\dist\main.js:43881:44)    
at CMakeFileApiDriver.doInit (c:\Users\[...]\.vscode\extensions\ms-vscode.cmake-tools-1.7.3\dist\main.js:43905:101)    
at CMakeFileApiDriver._baseInit (c:\Users\[...]\.vscode\extensions\ms-vscode.cmake-tools-1.7.3\dist\main.js:46192:9)    
at Function.createDerived (c:\Users\[...]\.vscode\extensions\ms-vscode.cmake-tools-1.7.3\dist\main.js:46199:9)    
at CMakeTools._startNewCMakeDriver (c:\Users\[...]\.vscode\extensions\ms-vscode.cmake-tools-1.7.3\dist\main.js:39925:27)    
at c:\Users\[...]\.vscode\extensions\ms-vscode.cmake-tools-1.7.3\dist\main.js:40145:21    
at c:\Users\[...]\.vscode\extensions\ms-vscode.cmake-tools-1.7.3\dist\main.js:53761:36
```

### Platform and Versions

- **Operating System**: Windows_NT x64 10.0.18363
- **CMake Version**: cmake version 3.20.3
- **VSCode Version**: 1.56.2
- **CMake Tools Extension Version**: v1.7.3
- **Compiler/Toolchain**: clang version 12.0.0 and gcc version 8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project) both don't work

**Comment by e1kable** [comment]
It seems like the problem was that in the build directory already a CMakeFiles Folder existed

**Comment by bobbrow** [comment]
We should take a look at this case, so I'm reopening it.
