### ISSUE TITLE
Diagnostic severity levels are only recognized in english

### ISSUE THREAD

**Issue by danishbelal** [microsoft/vscode-cmake-tools#1959]
### Brief Issue Summary
Launching a target that emits warnings in non-english fails due to unknown severity levels.

### Steps to reproduce 
(make sure your output is non-english)

```
# CMakeLists.txt
add_executable(Demo main.cpp)
target_compile_options(Demo PRIVATE -Wall -Wextra)
```
```
// main.cpp
int main(int argc, char** argv)
{
    // This triggers an unused variable warning because argc and argv are unused.
    return 0;
}
```

This project cannot be launched through the launch button in the lower toolbar.  It yields:
`[rollbar] Unhandled exception: Unhandled Promise rejection: build Error: Unknown diagnostic severity level: Warnung {}`

### Expected:

The program should be launched.  

Also note that the launch succeeds when the launch button is pressed twice.  This is expected, because the program is already built and therefore no warnings will be emitted.  In order to reproduce this multiple times, you need to clean the project before reattempting the launch

### Apparent Behavior:

The severity level `Warnung` (german word for warning) is not recognized as a valid severity level.  Also see here: https://github.com/microsoft/vscode-cmake-tools/blob/develop/src/diagnostics/build.ts#L58

A possible solution is not to throw an error on unknown severity levels.  This is proposed in PR https://github.com/microsoft/vscode-cmake-tools/pull/1799

### CMake Tools Log

```
[main] Building folder: vscode-test 
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /tmp/vscode-test/build --config Debug --target all -j 6 --
[build] [1/2  50% :: 0.024] Building CXX object CMakeFiles/Demo.dir/main.o
[build] ../main.cpp: In Funktion »int main(int, char**)«:
[build] ../main.cpp:1:14: Warnung: unverwendeter Parameter »argc« [-Wunused-parameter]
[build]     1 | int main(int argc, char** argv)
[build]       |          ~~~~^~~~
[build] ../main.cpp:1:27: Warnung: unverwendeter Parameter »argv« [-Wunused-parameter]
[build]     1 | int main(int argc, char** argv)
[build]       |                    ~~~~~~~^~~~
[build] [2/2 100% :: 0.099] Linking CXX executable Demo
[build] Build finished with exit code 0
[rollbar] Unhandled exception: Unhandled Promise rejection: build Error: Unknown diagnostic severity level: Warnung {}
```

### Developer Tools Log

```
[Extension Host] [CMakeTools] 2021-06-28T20:04:50.757Z [debug] [extension] [9909] cmake.launchTarget started
console.ts:137 [Extension Host] [CMakeTools] 2021-06-28T20:04:50.787Z [info] [main] Building folder: vscode-test Demo
console.ts:137 [Extension Host] [CMakeTools] 2021-06-28T20:04:50.804Z [debug] [main] Saving open files before configure/build
console.ts:137 [Extension Host] [CMakeTools] 2021-06-28T20:04:50.853Z [info] [build] Starting build
console.ts:137 [Extension Host] [CMakeTools] 2021-06-28T20:04:50.882Z [debug] [driver] Start build Demo
console.ts:137 [Extension Host] [CMakeTools] 2021-06-28T20:04:50.905Z [info] [proc] Executing command: /usr/bin/cmake --build /tmp/vscode-test/build --config Debug --target Demo -j 6 --
console.ts:137 [Extension Host] [CMakeTools] 2021-06-28T20:04:50.948Z [info] [build] [1/2  50% :: 0.025] Building CXX object CMakeFiles/Demo.dir/main.o
console.ts:137 [Extension Host] [CMakeTools] 2021-06-28T20:04:50.949Z [info] [build] ../main.cpp: In Funktion »int main(int, char**)«:
console.ts:137 [Extension Host] [CMakeTools] 2021-06-28T20:04:50.960Z [info] [build] ../main.cpp:1:14: Warnung: unverwendeter Parameter »argc« [-Wunused-parameter]
console.ts:137 [Extension Host] [CMakeTools] 2021-06-28T20:04:50.960Z [info] [build]     1 | int main(int argc, char** argv)
console.ts:137 [Extension Host] [CMakeTools] 2021-06-28T20:04:50.960Z [info] [build]       |          ~~~~^~~~
console.ts:137 [Extension Host] [CMakeTools] 2021-06-28T20:04:50.960Z [info] [build] ../main.cpp:1:27: Warnung: unverwendeter Parameter »argv« [-Wunused-parameter]
console.ts:137 [Extension Host] [CMakeTools] 2021-06-28T20:04:50.960Z [info] [build]     1 | int main(int argc, char** argv)
console.ts:137 [Extension Host] [CMakeTools] 2021-06-28T20:04:50.961Z [info] [build]       |                    ~~~~~~~^~~~
console.ts:137 [Extension Host] [CMakeTools] 2021-06-28T20:04:51.035Z [info] [build] [2/2 100% :: 0.114] Linking CXX executable Demo
console.ts:137 [Extension Host] [CMakeTools] 2021-06-28T20:04:51.036Z [debug] [cmakefileapi-parser] Read reply folder: /tmp/vscode-test/build/.cmake/api/v1/reply
console.ts:137 [Extension Host] [CMakeTools] 2021-06-28T20:04:51.037Z [debug] [cmakefileapi-parser] Found index files: ["cache-v2-cf0495f69ab71a4b3701.json","codemodel-v2-598cf1e90422da75c08b.json","index-2021-06-28T19-47-18-0243.json","target-Demo-Debug-0504e811b8a85f925c3f.json","toolchains-v1-5b03af47d70613e6973f.json"]
console.ts:137 [Extension Host] [CMakeTools] 2021-06-28T20:04:51.045Z [debug] [driver] Run _refreshExpansions
console.ts:137 [Extension Host] [CMakeTools] 2021-06-28T20:04:51.045Z [debug] [driver] Run _refreshExpansions cb
console.ts:137 [Extension Host] [CMakeTools] 2021-06-28T20:04:51.067Z [info] [build] Build finished with exit code 0
console.ts:137 [Extension Host] [CMakeTools] 2021-06-28T20:04:51.067Z [debug] [cache] Reading CMake cache file /tmp/vscode-test/build/CMakeCache.txt
console.ts:137 [Extension Host] [CMakeTools] 2021-06-28T20:04:51.069Z [debug] [cache] Parsing CMake cache string
console.ts:137 [Extension Host] [CMakeTools] 2021-06-28T20:04:51.083Z [fatal] [rollbar] Unhandled exception: Unhandled Promise rejection: launchTarget Error: Unknown diagnostic severity level: Warnung {}
S @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
_ @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
console.ts:137 [Extension Host] Error: Unknown diagnostic severity level: Warnung	at severity_of (/home/dbelal/.vscode-oss/extensions/ms-vscode.cmake-tools-1.7.3/dist/main.js:42829:19)	at /home/dbelal/.vscode-oss/extensions/ms-vscode.cmake-tools-1.7.3/dist/main.js:42841:89	at Array.map (<anonymous>)	at /home/dbelal/.vscode-oss/extensions/ms-vscode.cmake-tools-1.7.3/dist/main.js:42839:26	at Array.map (<anonymous>)	at CompileOutputConsumer.resolveDiagnostics (/home/dbelal/.vscode-oss/extensions/ms-vscode.cmake-tools-1.7.3/dist/main.js:42838:50)	at /home/dbelal/.vscode-oss/extensions/ms-vscode.cmake-tools-1.7.3/dist/main.js:40508:61	at runMicrotasks (<anonymous>)	at processTicksAndRejections (internal/process/task_queues.js:93:5)
S @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
_ @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
notificationsAlerts.ts:40 Running the contributed command: 'cmake.launchTarget' failed.
onDidChangeNotification @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:622
addNotification @ notifications.ts:206
error @ notificationService.ts:92
executeCommand @ statusbarPart.ts:899
processTicksAndRejections @ internal/process/task_queues.js:93
async function (async)
executeCommand @ statusbarPart.ts:897
(anonymous) @ statusbarPart.ts:853
console.ts:137 [Extension Host] provideCustomConfiguration
```

### Platform and Versions

- **Operating System**: Linux
- **CMake Version**: 3.20.3
- **VSCode Version**: 1.56.2
- **CMake Tools Extension Version**: 1.7.3
- **Compiler/Toolchain**: Any, but in my case g++ 11.1.0

**Comment by andreeis** [comment]
@danishbelal, thank you for opening this report. We may resolve it as a duplicate but we'll brainstorm first if there is anything additional to do besides the PR https://github.com/microsoft/vscode-cmake-tools/pull/1799 and its own active issue https://github.com/microsoft/vscode-cmake-tools/issues/1796.

**Comment by bilderbuchi** [comment]
@andreeis I think I have a similar/related issue - I get a
```
[rollbar] Unhandled exception: Unhandled Promise rejection: build Error: Unknown diagnostic severity level: Warning {}
```
Note that "Warning" is capitalised (emitted by gfortran) -- I'm not familiar with the code/language [here](https://github.com/microsoft/vscode-cmake-tools/blob/0c5dc2c0d2c06f550e7e1199fab6823da0d3c074/src/diagnostics/build.ts#L42-L61) to confidently judge if that comparison (or the incoming string argument ) is case-insensitive? If not, I think it should be?
