### ISSUE TITLE
Unable to parse CMakePresets.json file generated by VS

### ISSUE THREAD

**Issue by xisui-MSFT** [microsoft/vscode-cmake-tools#2396]
### Brief Issue Summary

I tried to open a CMake project generated by VS (32119.88.main) in VS Code (1.64.2, with CMake Tools 1.9.2 installed), and got the following error:

[presetController] Failed to parse CMakePresets.json: 
	SyntaxError: Unexpected token ﻿ in JSON at position 0
    at JSON.parse (<anonymous>)
    at PresetsController.parsePresetsFile (c:\Users\xisui\.vscode\extensions\ms-vscode.cmake-tools-1.9.2\dist\main.js:60445:36)
    at PresetsController.resetPresetsFile (c:\Users\xisui\.vscode\extensions\ms-vscode.cmake-tools-1.9.2\dist\main.js:59782:38)
    at PresetsController.reapplyPresets (c:\Users\xisui\.vscode\extensions\ms-vscode.cmake-tools-1.9.2\dist\main.js:59797:9)
    at watchPresetsChange (c:\Users\xisui\.vscode\extensions\ms-vscode.cmake-tools-1.9.2\dist\main.js:59699:13)
    at Function.init (c:\Users\xisui\.vscode\extensions\ms-vscode.cmake-tools-1.9.2\dist\main.js:59727:9)
    at Function.init (c:\Users\xisui\.vscode\extensions\ms-vscode.cmake-tools-1.9.2\dist\main.js:55479:35)
    at CMakeToolsFolderController._addFolder (c:\Users\xisui\.vscode\extensions\ms-vscode.cmake-tools-1.9.2\dist\main.js:55727:22)
    at CMakeToolsFolderController.loadAllCurrent (c:\Users\xisui\.vscode\extensions\ms-vscode.cmake-tools-1.9.2\dist\main.js:55679:17)
    at ExtensionManager._init (c:\Users\xisui\.vscode\extensions\ms-vscode.cmake-tools-1.9.2\dist\main.js:54050:13)
    at Function.create (c:\Users\xisui\.vscode\extensions\ms-vscode.cmake-tools-1.9.2\dist\main.js:54102:9)
    at setup (c:\Users\xisui\.vscode\extensions\ms-vscode.cmake-tools-1.9.2\dist\main.js:55194:32)

Repro steps:
1. In latest VS 2022, create a new CMake project using the template.
![image](https://user-images.githubusercontent.com/44103947/155232716-36d004a2-68bc-402e-bdab-b145f66d7afe.png)
2. Close VS, and open this folder in VS Code. Check 

This might be an encoding issue. The file encoding of CMakePresets.json generated by VS is UTF-8 with BOM. Also, saving the file as UTF-8 in VS Code seems to work.

UTF-8 with bom DOES work using CMake (like `cmake --preset presetName`). So I think it makes sense to fix this issue in CMake tools.

**Comment by bobbrow** [comment]
Thanks for reporting this.  We should be able to use `bomstrip` in our implementation of `readFile` as suggested here: https://stackoverflow.com/questions/24356713/node-js-readfile-error-with-utf8-encoded-file-on-windows

**Comment by bobbrow** [comment]
This should be fixed in 1.10.2 (pre-release).
