### ISSUE TITLE
Activating extension 1.13.41 failed due to an error

### ISSUE THREAD

**Issue by vdilecce** [microsoft/vscode-cmake-tools#2968]
### Brief Issue Summary

The extension fails to activate.

OS: CentOS 7.9
VSCode: 1.74.3
CPPTools extension: 1.13.9

As a consequence, none of the commands (`cmake.selectConfigurePreset`, `cmake.logDiagnostic`, `cmake.resetState`) work.

The extension host log:

```log
2023-01-24 12:16:35.054 [info] Extension host with pid XXXXXX started
2023-01-24 12:16:35.054 [info] Skipping acquiring lock for /home/user/.config/Code/User/workspaceStorage/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.
2023-01-24 12:16:35.174 [info] ExtensionService#_doActivateExtension ms-vscode.cpptools, startup: false, activationEvent: 'onLanguage:cpp'
2023-01-24 12:16:35.174 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
2023-01-24 12:16:35.174 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2023-01-24 12:16:36.037 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2023-01-24 12:16:36.037 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2023-01-24 12:16:36.528 [info] ExtensionService#_doActivateExtension ms-vscode.cmake-tools, startup: true, activationEvent: 'workspaceContains:*/CMakeLists.txt,*/*/CMakeLists.txt,*/*/*/CMakeLists.txt'
2023-01-24 12:16:36.596 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2023-01-24 12:16:37.349 [error] Activating extension ms-vscode.cmake-tools failed due to an error:
2023-01-24 12:16:37.349 [error] TypeError: Cannot read properties of undefined (reading 'tag')
	at warning (/home/user/.vscode/extensions/ms-vscode.cmake-tools-1.13.41/dist/main.js:47260:49)
	at showErrors (/home/user/.vscode/extensions/ms-vscode.cmake-tools-1.13.41/dist/main.js:50093:17)
	at PresetsController.validatePresetsFile (/home/user/.vscode/extensions/ms-vscode.cmake-tools-1.13.41/dist/main.js:50104:17)
	at async PresetsController.resetPresetsFile (/home/user/.vscode/extensions/ms-vscode.cmake-tools-1.13.41/dist/main.js:49279:23)
	at async PresetsController.reapplyPresets (/home/user/.vscode/extensions/ms-vscode.cmake-tools-1.13.41/dist/main.js:49290:9)
	at async PresetsController.init (/home/user/.vscode/extensions/ms-vscode.cmake-tools-1.13.41/dist/main.js:49214:9)
	at async CMakeProject.init (/home/user/.vscode/extensions/ms-vscode.cmake-tools-1.13.41/dist/main.js:34671:34)
	at async CMakeProject.create (/home/user/.vscode/extensions/ms-vscode.cmake-tools-1.13.41/dist/main.js:34880:9)
	at async ProjectController.createCMakeProjectsForWorkspaceFolder (/home/user/.vscode/extensions/ms-vscode.cmake-tools-1.13.41/dist/main.js:50575:27)
	at async ProjectController.addFolder (/home/user/.vscode/extensions/ms-vscode.cmake-tools-1.13.41/dist/main.js:50629:29)
	at async ProjectController.loadAllProjects (/home/user/.vscode/extensions/ms-vscode.cmake-tools-1.13.41/dist/main.js:50562:17)
	at async ExtensionManager.init (/home/user/.vscode/extensions/ms-vscode.cmake-tools-1.13.41/dist/main.js:43534:13)
	at async ExtensionManager.create (/home/user/.vscode/extensions/ms-vscode.cmake-tools-1.13.41/dist/main.js:43573:9)
	at async setup (/home/user/.vscode/extensions/ms-vscode.cmake-tools-1.13.41/dist/main.js:44706:36)
	at async v.n (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:7006)
	at async v.m (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:6969)
	at async v.l (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:6426)
2023-01-24 12:16:37.350 [info] Eager extensions activated
2023-01-24 12:16:37.388 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2023-01-24 12:16:37.389 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onStartupFinished'
2023-01-24 12:16:37.390 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2023-01-24 12:16:40.850 [warning] DiagnosticCollection with name 'C/C++' does already exist.
```

**Comment by vdilecce** [comment]
The `CMakePresets.json` is version 6 and contains package presets. Setting `cmake.AllowUnsupportedPresetsVersions` is `true`.

If I revert the `CMakePresets.json` to version 3 and remove the package presets, the extensions correctly activates.

**Comment by bobbrow** [comment]
Thank you for reporting this.  I will push a fix for this today.
