### ISSUE TITLE
Project configuration fails, Unhandled exception

### ISSUE THREAD

**Issue by julienlavergne** [microsoft/vscode-cmake-tools#3069]
### Brief Issue Summary

When configuring my project, vscode get stuck in a loop displaying following error:

`[rollbar] Unhandled exception: Failed to open CMake cache file on code model update TypeError: Cannot read properties of undefined (reading 'file') {}`

I was able to configure properly in the past, but for some reason it stopped working.
My workspace is a multi root workspace and only one project is getting configured with CMake. VSCode is on Windows and connecting to a Linux remote host using remote development extension. CMake is latest version 3.26.0 and is in the PATH.

I already tried to delete my build folder and reconfigure manually. I have also made sure there is no build folder in another other folder than the project I am configuring.

My .vscode/c_cpp_properties.json file:
```
{
    "configurations": [
        {
            "name": "Linux",
            "intelliSenseMode": "linux-gcc-x64",
            "configurationProvider": "ms-vscode.cmake-tools",
            "compileCommands": "${workspaceFolder}/build/compile_commands.json"
        }
    ],
    "version": 4
}
```

### CMake Tools Diagnostics

```shell
{
  "os": "linux",
  "vscodeVersion": "1.76.2",
  "cmtVersion": "1.14.18",
  "configurations": [
    {
      "folder": "[REDACTED]/projectA",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "[REDACTED]/projectB",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "[REDACTED]/projectC",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "[REDACTED]/projectD",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "[REDACTED]/projectE",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "[REDACTED]/projectF",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "[REDACTED]/projectG",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "[REDACTED]/projectH",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "[REDACTED]/projectI",
      "cmakeVersion": "3.26.0",
      "configured": false,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "[REDACTED]/projectJ",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "[REDACTED]/projectK",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": false
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    }
  ]
}
```

### Debug Log

```shell
[main] Safe constructing new CMakeProject instance
[variant] Constructing VariantManager
[main] Constructing new CMakeProject instance
[main] Starting CMake Tools second-phase init
[variant] Loaded new set of variants
[kit] Not reading non-existent kits file: /export/home/jlav/.local/share/CMakeTools/cmake-tools-kits.json
[kit] Not reading non-existent kits file: [REDACTED]/projectA/.vscode/cmake-kits.json
[main] Injecting new Kit into CMake driver
[main] CMakeProject instance initialization complete.
[main] Safe constructing new CMakeProject instance
[variant] Constructing VariantManager
[main] Constructing new CMakeProject instance
[main] Starting CMake Tools second-phase init
[variant] Loaded new set of variants
[kit] Not reading non-existent kits file: /export/home/jlav/.local/share/CMakeTools/cmake-tools-kits.json
[kit] Not reading non-existent kits file: [REDACTED]/projectB/.vscode/cmake-kits.json
[main] CMakeProject instance initialization complete.
[main] Safe constructing new CMakeProject instance
[variant] Constructing VariantManager
[main] Constructing new CMakeProject instance
[main] Starting CMake Tools second-phase init
[variant] Loaded new set of variants
[kit] Not reading non-existent kits file: /export/home/jlav/.local/share/CMakeTools/cmake-tools-kits.json
[extension] Configuring workspace on open [REDACTED]/projectA
[kit] Not reading non-existent kits file: [REDACTED]/projectC/.vscode/cmake-kits.json
[proc] Executing command: /opt/tools/cmake/bin/cmake --version
[main] CMakeProject instance initialization complete.
[main] Safe constructing new CMakeProject instance
[variant] Constructing VariantManager
[main] Constructing new CMakeProject instance
[main] Starting CMake Tools second-phase init
[main] Starting new CMake driver
[main] Starting CMake driver
[cmakefileapi-driver] Creating instance of CMakeFileApiDriver
[driver] Initializating base driver using kit
[driver] CMakeDriver Kit set to __unspec__
[kit] The environment for kit '__unspec__': {
  "MANPATH": ":/opt/puppetlabs/puppet/share/man",
  "SHELL": "/bin/bash",
  "TMPDIR": "/export/home/jlav/tmp",
  "SSH_CLIENT": "[REDACTED] 50081 22",
  "VAULT_ADDR": "[REDACTED]",
  "GTEST_COLOR": "1",
  "http_proxy": "http://127.0.0.1:23127",
  "USER": "jlav",
  "LS_COLORS": "",
  "NO_STATUS": "1",
  "SSH_AUTH_SOCK": "/tmp/vscode-ssh-auth-sock-159397797",
  "VSCODE_AGENT_FOLDER": "/export/home/jlav/.vscode-server",
  "MAIL": "/var/spool/mail/jlav",
  "PATH":[REDACTED],
  "PWD": "/export/home/jlav",
  "LANG": "C",
  "https_proxy": "http://127.0.0.1:23127",
  "HTTPS_PROXY": "http://127.0.0.1:23127",
  "SHLVL": "4",
  "HOME": "/export/home/jlav",
  "HTTP_PROXY": "http://127.0.0.1:23127",
  "TMP": "/export/home/jlav/tmp",
  "LOGNAME": "jlav",
  "SSH_CONNECTION": "[REDACTED] 50081 [REDACTED] 22",
  "LESSOPEN": "||/usr/bin/lesspipe.sh %s",
  "VAULT_NAMESPACE": "[REDACTED]",
  "_": "/export/home/jlav/.vscode-server/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/node",
  "VSCODE_HANDLES_SIGPIPE": "true",
  "HOSTNAME": "[REDACTED]",
  "HISTSIZE": "1000",
  "HISTCONTROL": "ignoredups",
  "VSCODE_AMD_ENTRYPOINT": "vs/workbench/api/node/extensionHostProcess",
  "VSCODE_HANDLES_UNCAUGHT_ERRORS": "true",
  "VSCODE_NLS_CONFIG": "{\"locale\":\"en\",\"availableLanguages\":{}}",
  "BROWSER": "/export/home/jlav/.vscode-server/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/bin/helpers/browser.sh",
  "VSCODE_CWD": "/export/home/jlav",
  "ELECTRON_RUN_AS_NODE": "1",
  "VSCODE_IPC_HOOK_CLI": "/export/home/jlav/tmp/vscode-ipc-1d4dd13c-9afe-40d2-b80e-130bf47fd4a7.sock",
  "VSCODE_L10N_BUNDLE_LOCATION": ""
}
[driver] Trying to detect generator supported by system
[cache] Reading CMake cache file [REDACTED]/projectA/build/CMakeCache.txt
[variant] Loaded new set of variants
[cache] Parsing CMake cache string
[cache] Reading CMake cache file [REDACTED]/projectA/build/CMakeCache.txt
[kit] Not reading non-existent kits file: /export/home/jlav/.local/share/CMakeTools/cmake-tools-kits.json
[cache] Parsing CMake cache string
[cmakefileapi-parser] Read reply folder: [REDACTED]/projectA/build/.cmake/api/v1/reply
[cmakefileapi-parser] Found index files: ["cache-v2-9e82f784970310eccb10.json","cmakeFiles-v1-56c98b669b0eb76f2f96.json","codemodel-v2-df1800008ab87a239da1.json",[REDACTED],"toolchains-v1-05ca3ff5362bdd026ef5.json"]
[extension] Attempting to use cache to configure workspace file://[REDACTED]/projectB
[main] Not starting CMake driver: no kit selected
[main] Unable to configure with existing cache
[kit] Not reading non-existent kits file: [REDACTED]/projectD/.vscode/cmake-kits.json
[main] CMakeProject instance initialization complete.
[main] Safe constructing new CMakeProject instance
[variant] Constructing VariantManager
[main] Constructing new CMakeProject instance
[main] Starting CMake Tools second-phase init
[variant] Loaded new set of variants
[kit] Not reading non-existent kits file: /export/home/jlav/.local/share/CMakeTools/cmake-tools-kits.json
[kit] Not reading non-existent kits file: [REDACTED]/projectE/.vscode/cmake-kits.json
[main] CMakeProject instance initialization complete.
[main] Safe constructing new CMakeProject instance
[variant] Constructing VariantManager
[main] Constructing new CMakeProject instance
[main] Starting CMake Tools second-phase init
[driver] Setting new variant Release
[variant] Loaded new set of variants
[kit] Not reading non-existent kits file: /export/home/jlav/.local/share/CMakeTools/cmake-tools-kits.json
[kit] Not reading non-existent kits file: [REDACTED]/projectF/.vscode/cmake-kits.json
[main] CMakeProject instance initialization complete.
[main] Safe constructing new CMakeProject instance
[variant] Constructing VariantManager
[main] Constructing new CMakeProject instance
[main] Starting CMake Tools second-phase init
[variant] Loaded new set of variants
[kit] Not reading non-existent kits file: /export/home/jlav/.local/share/CMakeTools/cmake-tools-kits.json
[kit] Not reading non-existent kits file: [REDACTED]/projectG/.vscode/cmake-kits.json
[main] CMakeProject instance initialization complete.
[main] Safe constructing new CMakeProject instance
[variant] Constructing VariantManager
[main] Constructing new CMakeProject instance
[main] Starting CMake Tools second-phase init
[variant] Loaded new set of variants
[kit] Not reading non-existent kits file: /export/home/jlav/.local/share/CMakeTools/cmake-tools-kits.json
[kit] Not reading non-existent kits file: [REDACTED]/projectH/.vscode/cmake-kits.json
[main] CMakeProject instance initialization complete.
[main] Safe constructing new CMakeProject instance
[variant] Constructing VariantManager
[main] Constructing new CMakeProject instance
[main] Starting CMake Tools second-phase init
[variant] Loaded new set of variants
[kit] Not reading non-existent kits file: /export/home/jlav/.local/share/CMakeTools/cmake-tools-kits.json
[extension] Attempting to use cache to configure workspace file://[REDACTED]/projectC
[main] Not starting CMake driver: no kit selected
[main] Unable to configure with existing cache
[kit] Not reading non-existent kits file: [REDACTED]/projectI/.vscode/cmake-kits.json
[main] Starting new CMake driver
[main] Starting CMake driver
[cmakefileapi-driver] Creating instance of CMakeFileApiDriver
[driver] Initializating base driver using kit
[driver] CMakeDriver Kit set to __unspec__
[kit] The environment for kit '__unspec__': {
  "MANPATH": ":/opt/puppetlabs/puppet/share/man",
  "SHELL": "/bin/bash",
  "TMPDIR": "/export/home/jlav/tmp",
  "SSH_CLIENT": "[REDACTED] 50081 22",
  "VAULT_ADDR": "[REDACTED]",
  "GTEST_COLOR": "1",
  "http_proxy": "http://127.0.0.1:23127",
  "USER": "jlav",
  "LS_COLORS": "",
  "NO_STATUS": "1",
  "SSH_AUTH_SOCK": "/tmp/vscode-ssh-auth-sock-159397797",
  "VSCODE_AGENT_FOLDER": "/export/home/jlav/.vscode-server",
  "MAIL": "/var/spool/mail/jlav",
  "PATH":[REDACTED],
  "PWD": "/export/home/jlav",
  "LANG": "C",
  "https_proxy": "http://127.0.0.1:23127",
  "HTTPS_PROXY": "http://127.0.0.1:23127",
  "SHLVL": "4",
  "HOME": "/export/home/jlav",
  "HTTP_PROXY": "http://127.0.0.1:23127",
  "TMP": "/export/home/jlav/tmp",
  "LOGNAME": "jlav",
  "SSH_CONNECTION": "[REDACTED] 50081 [REDACTED] 22",
  "LESSOPEN": "||/usr/bin/lesspipe.sh %s",
  "VAULT_NAMESPACE": "[REDACTED]",
  "_": "/export/home/jlav/.vscode-server/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/node",
  "VSCODE_HANDLES_SIGPIPE": "true",
  "HOSTNAME": "[REDACTED]",
  "HISTSIZE": "1000",
  "HISTCONTROL": "ignoredups",
  "VSCODE_AMD_ENTRYPOINT": "vs/workbench/api/node/extensionHostProcess",
  "VSCODE_HANDLES_UNCAUGHT_ERRORS": "true",
  "VSCODE_NLS_CONFIG": "{\"locale\":\"en\",\"availableLanguages\":{}}",
  "BROWSER": "/export/home/jlav/.vscode-server/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/bin/helpers/browser.sh",
  "VSCODE_CWD": "/export/home/jlav",
  "ELECTRON_RUN_AS_NODE": "1",
  "VSCODE_IPC_HOOK_CLI": "/export/home/jlav/tmp/vscode-ipc-1d4dd13c-9afe-40d2-b80e-130bf47fd4a7.sock",
  "VSCODE_L10N_BUNDLE_LOCATION": ""
}
[driver] Trying to detect generator supported by system
[main] Injecting new Kit into CMake driver
[cache] Reading CMake cache file [REDACTED]/projectA/build/CMakeCache.txt
[cache] Parsing CMake cache string
[cache] Reading CMake cache file [REDACTED]/projectA/build/CMakeCache.txt
[cache] Parsing CMake cache string
[cmakefileapi-parser] Read reply folder: [REDACTED]/projectA/build/.cmake/api/v1/reply
[cmakefileapi-parser] Found index files: ["cache-v2-9e82f784970310eccb10.json","cmakeFiles-v1-56c98b669b0eb76f2f96.json","codemodel-v2-df1800008ab87a239da1.json",[REDACTED],"toolchains-v1-05ca3ff5362bdd026ef5.json"]
[extension] Attempting to use cache to configure workspace file://[REDACTED]/projectD
[extension] Attempting to use cache to configure workspace file://[REDACTED]/projectE
[main] Not starting CMake driver: no kit selected
[main] Not starting CMake driver: no kit selected
[main] Unable to configure with existing cache
[main] Unable to configure with existing cache
[extension] Attempting to use cache to configure workspace file://[REDACTED]/projectF
[main] Not starting CMake driver: no kit selected
[main] Unable to configure with existing cache
[extension] Attempting to use cache to configure workspace file://[REDACTED]/projectG
[main] Not starting CMake driver: no kit selected
[main] Unable to configure with existing cache
[main] CMakeProject instance initialization complete.
[main] Safe constructing new CMakeProject instance
[variant] Constructing VariantManager
[main] Constructing new CMakeProject instance
[main] Starting CMake Tools second-phase init
[extension] Attempting to use cache to configure workspace file://[REDACTED]/projectH
[main] Not starting CMake driver: no kit selected
[main] Unable to configure with existing cache
[variant] Loaded new set of variants
[kit] Not reading non-existent kits file: /export/home/jlav/.local/share/CMakeTools/cmake-tools-kits.json
[kit] Not reading non-existent kits file: [REDACTED]/projectJ/.vscode/cmake-kits.json
[main] CMakeProject instance initialization complete.
[main] Safe constructing new CMakeProject instance
[variant] Constructing VariantManager
[main] Constructing new CMakeProject instance
[main] Starting CMake Tools second-phase init
[driver] Setting new variant Release
[variant] Loaded new set of variants
[kit] Not reading non-existent kits file: /export/home/jlav/.local/share/CMakeTools/cmake-tools-kits.json
[kit] Not reading non-existent kits file: [REDACTED]/projectK/.vscode/cmake-kits.json
[main] CMakeProject instance initialization complete.
[extension] Attempting to use cache to configure workspace file://[REDACTED]/projectJ
[main] Not starting CMake driver: no kit selected
[main] Unable to configure with existing cache
[rollbar] Unhandled exception: Failed to open CMake cache file on code model update TypeError: Cannot read properties of undefined (reading 'file') {}
[extension] Attempting to use cache to configure workspace file://[REDACTED]/projectK
[main] Not starting CMake driver: no kit selected
[main] Unable to configure with existing cache
[main] Starting new CMake driver
[main] Starting CMake driver
[cmakefileapi-driver] Creating instance of CMakeFileApiDriver
[driver] Initializating base driver using kit
[driver] CMakeDriver Kit set to __unspec__
[kit] The environment for kit '__unspec__': {
  "MANPATH": ":/opt/puppetlabs/puppet/share/man",
  "SHELL": "/bin/bash",
  "TMPDIR": "/export/home/jlav/tmp",
  "SSH_CLIENT": "[REDACTED] 50081 22",
  "VAULT_ADDR": "[REDACTED]",
  "GTEST_COLOR": "1",
  "http_proxy": "http://127.0.0.1:23127",
  "USER": "jlav",
  "LS_COLORS": "",
  "NO_STATUS": "1",
  "SSH_AUTH_SOCK": "/tmp/vscode-ssh-auth-sock-159397797",
  "VSCODE_AGENT_FOLDER": "/export/home/jlav/.vscode-server",
  "MAIL": "/var/spool/mail/jlav",
  "PATH":[REDACTED],
  "PWD": "/export/home/jlav",
  "LANG": "C",
  "https_proxy": "http://127.0.0.1:23127",
  "HTTPS_PROXY": "http://127.0.0.1:23127",
  "SHLVL": "4",
  "HOME": "/export/home/jlav",
  "HTTP_PROXY": "http://127.0.0.1:23127",
  "TMP": "/export/home/jlav/tmp",
  "LOGNAME": "jlav",
  "SSH_CONNECTION": "[REDACTED] 50081 [REDACTED] 22",
  "LESSOPEN": "||/usr/bin/lesspipe.sh %s",
  "VAULT_NAMESPACE": "[REDACTED]",
  "_": "/export/home/jlav/.vscode-server/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/node",
  "VSCODE_HANDLES_SIGPIPE": "true",
  "HOSTNAME": "[REDACTED]",
  "HISTSIZE": "1000",
  "HISTCONTROL": "ignoredups",
  "VSCODE_AMD_ENTRYPOINT": "vs/workbench/api/node/extensionHostProcess",
  "VSCODE_HANDLES_UNCAUGHT_ERRORS": "true",
  "VSCODE_NLS_CONFIG": "{\"locale\":\"en\",\"availableLanguages\":{}}",
  "BROWSER": "/export/home/jlav/.vscode-server/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/bin/helpers/browser.sh",
  "VSCODE_CWD": "/export/home/jlav",
  "ELECTRON_RUN_AS_NODE": "1",
  "VSCODE_IPC_HOOK_CLI": "/export/home/jlav/tmp/vscode-ipc-1d4dd13c-9afe-40d2-b80e-130bf47fd4a7.sock",
  "VSCODE_L10N_BUNDLE_LOCATION": ""
}
[driver] Trying to detect generator supported by system
[cache] Reading CMake cache file [REDACTED]/projectA/build/CMakeCache.txt
[cache] Parsing CMake cache string
[cache] Reading CMake cache file [REDACTED]/projectA/build/CMakeCache.txt
[cache] Parsing CMake cache string
[cmakefileapi-parser] Read reply folder: [REDACTED]/projectA/build/.cmake/api/v1/reply
[cmakefileapi-parser] Found index files: ["cache-v2-9e82f784970310eccb10.json","cmakeFiles-v1-56c98b669b0eb76f2f96.json","codemodel-v2-df1800008ab87a239da1.json",[REDACTED],"toolchains-v1-05ca3ff5362bdd026ef5.json"]
[driver] Setting new variant Release
[rollbar] Unhandled exception: Failed to open CMake cache file on code model update TypeError: Cannot read properties of undefined (reading 'file') {}
[main] Starting new CMake driver
[main] Starting CMake driver
[cmakefileapi-driver] Creating instance of CMakeFileApiDriver
[driver] Initializating base driver using kit
[driver] CMakeDriver Kit set to __unspec__
[kit] The environment for kit '__unspec__': {
  "MANPATH": ":/opt/puppetlabs/puppet/share/man",
  "SHELL": "/bin/bash",
  "TMPDIR": "/export/home/jlav/tmp",
  "SSH_CLIENT": "[REDACTED] 50081 22",
  "VAULT_ADDR": "[REDACTED]",
  "GTEST_COLOR": "1",
  "http_proxy": "http://127.0.0.1:23127",
  "USER": "jlav",
  "LS_COLORS": "",
  "NO_STATUS": "1",
  "SSH_AUTH_SOCK": "/tmp/vscode-ssh-auth-sock-159397797",
  "VSCODE_AGENT_FOLDER": "/export/home/jlav/.vscode-server",
  "MAIL": "/var/spool/mail/jlav",
  "PATH":[REDACTED],
  "PWD": "/export/home/jlav",
  "LANG": "C",
  "https_proxy": "http://127.0.0.1:23127",
  "HTTPS_PROXY": "http://127.0.0.1:23127",
  "SHLVL": "4",
  "HOME": "/export/home/jlav",
  "HTTP_PROXY": "http://127.0.0.1:23127",
  "TMP": "/export/home/jlav/tmp",
  "LOGNAME": "jlav",
  "SSH_CONNECTION": "[REDACTED] 50081 [REDACTED] 22",
  "LESSOPEN": "||/usr/bin/lesspipe.sh %s",
  "VAULT_NAMESPACE": "[REDACTED]",
  "_": "/export/home/jlav/.vscode-server/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/node",
  "VSCODE_HANDLES_SIGPIPE": "true",
  "HOSTNAME": "[REDACTED]",
  "HISTSIZE": "1000",
  "HISTCONTROL": "ignoredups",
  "VSCODE_AMD_ENTRYPOINT": "vs/workbench/api/node/extensionHostProcess",
  "VSCODE_HANDLES_UNCAUGHT_ERRORS": "true",
  "VSCODE_NLS_CONFIG": "{\"locale\":\"en\",\"availableLanguages\":{}}",
  "BROWSER": "/export/home/jlav/.vscode-server/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/bin/helpers/browser.sh",
  "VSCODE_CWD": "/export/home/jlav",
  "ELECTRON_RUN_AS_NODE": "1",
  "VSCODE_IPC_HOOK_CLI": "/export/home/jlav/tmp/vscode-ipc-1d4dd13c-9afe-40d2-b80e-130bf47fd4a7.sock",
  "VSCODE_L10N_BUNDLE_LOCATION": ""
}
[driver] Trying to detect generator supported by system
[cache] Reading CMake cache file [REDACTED]/projectA/build/CMakeCache.txt
[cache] Parsing CMake cache string
[cache] Reading CMake cache file [REDACTED]/projectA/build/CMakeCache.txt
[cache] Parsing CMake cache string
[cmakefileapi-parser] Read reply folder: [REDACTED]/projectA/build/.cmake/api/v1/reply
[cmakefileapi-parser] Found index files: ["cache-v2-9e82f784970310eccb10.json","cmakeFiles-v1-56c98b669b0eb76f2f96.json","codemodel-v2-df1800008ab87a239da1.json",[REDACTED],"toolchains-v1-05ca3ff5362bdd026ef5.json"]
[driver] Setting new variant Release
[rollbar] Unhandled exception: Failed to open CMake cache file on code model update TypeError: Cannot read properties of undefined (reading 'file') {}
[main] Starting new CMake driver
[main] Starting CMake driver
[cmakefileapi-driver] Creating instance of CMakeFileApiDriver
[driver] Initializating base driver using kit
[driver] CMakeDriver Kit set to __unspec__
```

### Additional Information
In Developer Tools console
```
  ERR [Extension Host] TypeError: Cannot read properties of undefined (reading 'file')
	at /export/home/jlav/.vscode-server/extensions/ms-vscode.cmake-tools-1.14.18/dist/main.js:38634:117
	at Array.forEach (<anonymous>)
	at CTestDriver.refreshTests (/export/home/jlav/.vscode-server/extensions/ms-vscode.cmake-tools-1.14.18/dist/main.js:38633:30)
	at async CMakeProject.startNewCMakeDriver (/export/home/jlav/.vscode-server/extensions/ms-vscode.cmake-tools-1.14.18/dist/main.js:34583:9)
	at async /export/home/jlav/.vscode-server/extensions/ms-vscode.cmake-tools-1.14.18/dist/main.js:34818:21
	at async /export/home/jlav/.vscode-server/extensions/ms-vscode.cmake-tools-1.14.18/dist/main.js:52921:36
```

_No response_

**Comment by snehara99** [comment]
Thank you for reaching out with this issue. We will look into it and will reach out if we have more questions.

**Comment by xisui-MSFT** [comment]
@julienlavergne Looks like your test info is of different format than what we used to test. Can you please do the following:
- Do CMake configure
- In a terminal, cd to the directory containing file CTestTestfile.cmake (likely the same directly as CMakeCache.txt)
- run `ctest --show-only=json-v1 -C <build config>`, where <build config> is something like Debug. And share the output. You may want to hide some of the file names.

Thanks!

**Comment by julienlavergne** [comment]
I have a large number of `CTestTestfile.cmake` files, one of them is indeed in the root build folder, next to the CMakeCache.txt.

In that folder, output of `ctest --show-only=json-v1 -C Debug` is very large also. I give you a part of it and removed stuff that only differ by file names. Let me know if need the whole thing.
```
{
  "backtraceGraph" :
  {
    "commands" : [],
    "files" : [],
    "nodes" : []
  },
  "kind" : "ctestInfo",
  "tests" :
  [
    {
      "command" :
      [
        "[REDACTED_CMAKE_BUILD_DIRECTORY]/bin/[REDACTED_TEST_NAME]Test",
        "--gtest_filter=[REDACTED]",
        "--gtest_also_run_disabled_tests"
      ],
      "config" : "Debug",
      "name" : "[REDACTED_FULLY_QUALIFIED_TEST_NAME]",
      "properties" :
      [
        {
          "name" : "SKIP_REGULAR_EXPRESSION",
          "value" :
          [
            "\\[  SKIPPED \\]"
          ]
        },
        {
          "name" : "WORKING_DIRECTORY",
          "value" : "[REDACTED_CMAKE_BUILD_DIRECTORY]/core/tests"
        }
      ]
    },
	... [REDACTED: same thing as above with different tests in different folders]
	{
      "config" : "Debug",
      "name" : "[REDACTED_TEST_NAME]Test_NOT_BUILT",
      "properties" :
      [
        {
          "name" : "WORKING_DIRECTORY",
          "value" : "[REDACTED_CMAKE_BUILD_DIRECTORY]/[OTHER_DIRECTORY]/tests"
        }
      ]
    },
	... [REDACTED: same thing as above with different tests in different folders]
	],
  "version" :
  {
    "major" : 1,
    "minor" : 0
  }
}
```

**Comment by guntern** [comment]
It appears that I ran into the same or at least a similar issue. I do have the same infinite loop in one project. But it does not matter, whether the project is part of a multiroot workspace or opened as its own workspace. Other (way simpler) projects work just fine.

**Comment by xisui-MSFT** [comment]
Looks like there's no backtrace information in `CTestTestfile.cmake`. Are you aware of any settings in your projects removing/suppressing this info?

Anyway, I'll create a PR to fix this issue today.

**Comment by julienlavergne** [comment]
We are using googletest and the list of test is generated dynamically. On a clean configure, all the tests listed by `ctest --show-only=json-v1 -C Debug` are "NOT_BUILT" and show no command.

When we add a native ctest to our cmake `add_test(NAME dummytest COMMAND echo toto)`, we indeed have a backtrace info. So it looks like its only with our google tests when using `gtest_discover_tests`

**Comment by guntern** [comment]
For me its Catch2 with `catch_discover_tests` and also an empty backtraceGraph.

**Comment by guntern** [comment]
@xisui-MSFT . Thank you very much for the fast fix. I can enable testing again and do not have an infinite loop anymore. However, during `CMake: Configure` I still get one instance of the above mentioned unhandled exception.

**Comment by guntern** [comment]
One thing though: The fix made me curious about the test explorer. I tried `CMake: Refresh Tests` and also Tu run the tests under the testing ribbon. Somehow, this brought me back to the infinite loop of the exception. I tried to reproduce it, but did not manage.

On thing I noticed though: Without the exception loop, I cannot run the tests under `Testing`. It claims that there are no tests to be found. However, when running `ctest` within my `build`-directory the tests run fine. But this might be another issue, but it could also be related.

**Comment by xisui-MSFT** [comment]
@guntern Would be great if you can provide a consistent repro.

FYI, the test command we use is similar to "ctest  -R <test name> -C <build config> <other args in your config>" if you use kit + variants, or "cmake -T test --preset <preset> -R <test name>" if you use presets.

This test explorer is generic and designed to work for all setups using ctest, and so lack of some framework specific features. Since you mentioned that you use Catch2, you can probably also try extension "C++ TestMate".

**Comment by guntern** [comment]
> @guntern Would be great if you can provide a consistent repro.

I will try my best once more. So far it was not possible.
 
> FYI, the test command we use is similar to "ctest -R -C " if you use kit + variants, or "cmake -T test --preset -R " if you use presets.
> 
> This test explorer is generic and designed to work for all setups using ctest, and so lack of some framework specific features. Since you mentioned that you use Catch2, you can probably also try extension "C++ TestMate".

Thanks for the explanation. I actually suspect the `-R` part, because the things given afterwards may filter out my tests. But I will also check once more and might give C++TestMate a try as well. Thankk you very much for the advice.

**Comment by xisui-MSFT** [comment]
@guntern Edited my last message. Sorry I didn't realize there were escaping issues.

**Comment by guntern** [comment]
@xisui-MSFT I tried to reproduce the error today. It is hard.
1. Started VS Code with the workspace. It automatically tried to configure CMake. I ended up with the infinite loop of the above mentioned exception. Nothing to be done from my side to trigger this. Because of the loop I had to restartd
2. After the restart, the automatic configuring worked fine. I was able to configure again and again. Building worked, Refresh Tests worked. This time I even was able to run all the tests. And except for one the test results were correctly shown in the panel. Only one was marked as failed even though the output clearly stated that it was succesful.

So for now I am not able to have a consistent repro. But I will try again.

**Comment by xisui-MSFT** [comment]
@guntern 
1. Are all projects in the workspace set as configure on open?
2. Would be great if you can provide a repo on incorrectly reported test results too. Could be another corner case that I'm not aware of.

**Comment by guntern** [comment]
I now used my setup for a couple of days without any further issues. So it appears to be solved.

However, I am puzzled why I still saw the error with versions installed, which should have fixed the issue. Is there anything strange going on with the WSL setup so that I need multiple restarts of VS Code (and maybe the WSL) until the updates of VS Code and all extensions are done both in Windows and the WSL?

**Comment by xisui-MSFT** [comment]
@guntern Usually closing all VS Code instances and reopening is good enough. But you'll need to consult the VS Code team for more details.

**Comment by julienlavergne** [comment]
Issue is solved for me, so I close.
