### ISSUE TITLE
Getting a rollbar unhandled exception on every configure but it seems to work fine

### ISSUE THREAD

**Issue by jmml97** [microsoft/vscode-cmake-tools#3230]
### Brief Issue Summary

Whenever I configure my project I get the following error:

`[rollbar] Unhandled exception: Unhandled Promise rejection: configure SyntaxError: Unexpected token S in JSON at position 3 {}`

I think this has been happening for a week. Before then, this error did not appear. This problem does not seem to affect the configure itself, as CMake seems to configure and build correctly.

### CMake Tools Diagnostics

```shell
{
  "os": "linux",
  "vscodeVersion": "1.79.2",
  "cmtVersion": "1.14.34",
  "configurations": [
    {
      "folder": "/app",
      "cmakeVersion": "3.17.5",
      "configured": true,
      "generator": "Unix Makefiles",
      "usesPresets": false,
      "compilers": {
        "C": "/opt/rh/devtoolset-11/root/usr/bin/gcc",
        "CXX": "/opt/rh/devtoolset-11/root/usr/bin/g++"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [
      <I've redacted this file path>
    ],
    "responses": [
      {
        "uri": "file:///app/src/utils/xt_auth.cpp",
        "configuration": {
          "includePath": [
            <I've redacted the include paths>
          ],
          "defines": [],
          "compilerPath": "/opt/rh/devtoolset-11/root/usr/bin/g++",
          "compilerArgs": [],
          "compilerFragments": [
            " -Wall -Wextra -Wno-write-strings -g -DNOT_STABLE=1 -DTHREADS_ENABLED -DMAX_THREADS=6 -g  ",
            "-std=c++17"
          ]
        }
      }
    ],
    "partialMatches": [],
    "targetCount": 9,
    "executablesCount": 7,
    "librariesCount": 1,
    "targets": [
      <I've redacted the targets>
    ]
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": false
    }
  ]
}
```

### Debug Log

```shell
[main] Configuring project: app 
[main] Saving open files before configure/build
[driver] Start configure 
[driver] Running pre-configure checks and steps
[driver] Using compilers in GCC 11.2.1 x86_64-redhat-linux for configure
[cmakefileapi-driver] Configuring using kit
[cmakefileapi-driver] Invoking CMake cmake3 with arguments ["--no-warn-unused-cli","-DNOT_STABLE=1","-DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE","-DCMAKE_BUILD_TYPE:STRING=Debug","-DCMAKE_C_COMPILER:FILEPATH=/opt/rh/devtoolset-11/root/usr/bin/gcc","-DCMAKE_CXX_COMPILER:FILEPATH=/opt/rh/devtoolset-11/root/usr/bin/g++","-S/app","-B/app/build","-G","Unix Makefiles"]
[proc] Executing command: cmake3 --no-warn-unused-cli -DNOT_STABLE=1 -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/opt/rh/devtoolset-11/root/usr/bin/gcc -DCMAKE_CXX_COMPILER:FILEPATH=/opt/rh/devtoolset-11/root/usr/bin/g++ -S/app -B/app/build -G "Unix Makefiles"
[proc]   with environment: {<some environment variables I have redacted>,"_":"/usr/bin/cat","VSCODE_HANDLES_SIGPIPE":"true","VSCODE_AMD_ENTRYPOINT":"vs/workbench/api/node/extensionHostProcess","VSCODE_HANDLES_UNCAUGHT_ERRORS":"true","VSCODE_NLS_CONFIG":"{\"locale\":\"en\",\"osLocale\":\"en\",\"availableLanguages\":{}}","HISTSIZE":"1000","REMOTE_CONTAINERS_SOCKETS":"[\"/tmp/vscode-ssh-auth-ed31bb23-c560-4ef0-a772-6c418341dd89.sock\",\"/tmp/.X11-unix/X3\",\"/root/.gnupg/S.gpg-agent\"]","USER":"root","REMOTE_CONTAINERS_IPC":"/tmp/vscode-remote-containers-ipc-ed31bb23-c560-4ef0-a772-6c418341dd89.sock","MAIL":"/var/spool/mail/root","LANG":"en_US.UTF-8","HISTCONTROL":"ignoredups","LOGNAME":"root","LESSOPEN":"||/usr/bin/lesspipe.sh %s","SSH_AUTH_SOCK":"/tmp/vscode-ssh-auth-ed31bb23-c560-4ef0-a772-6c418341dd89.sock","DISPLAY":":3","REMOTE_CONTAINERS_DISPLAY_SOCK":"/tmp/.X11-unix/X3","REMOTE_CONTAINERS":"true","BROWSER":"/root/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/bin/helpers/browser.sh","VSCODE_CWD":"/root/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06","ELECTRON_RUN_AS_NODE":"1","VSCODE_IPC_HOOK_CLI":"/tmp/vscode-ipc-76a58392-1ac9-4208-9e23-2777326fac4c.sock","VSCODE_L10N_BUNDLE_LOCATION":"","APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL":"1"}
[cmake] Not searching for unused variables given on the command line.
[cmake] -- Configuring done
[cmake] -- Generating done
[cmake] -- Build files have been written to: /app/build
[cmakefileapi-parser] Read reply folder: /app/build/.cmake/api/v1/reply
[cmakefileapi-parser] Found index files: ["cache-v2-5ec225571c151aa0810c.json","cmakeFiles-v1-d89535ed2aa62b89ac55.json","codemodel-v2-4023ca5917254f6a4c8f.json","index-2023-07-04T10-50-26-0406.json", <some files related to my project I've redacted>]
[cache] Reading CMake cache file /app/build/CMakeCache.txt
[cache] Parsing CMake cache string
[rollbar] Unhandled exception: Unhandled Promise rejection: configure SyntaxError: Unexpected token S in JSON at position 3 {}
```

**Comment by snehara99** [comment]
Hi @jmml97, this seems to be similar to #3131 and #3144. We are looking into it currently, thanks for the report!

**Comment by snehara99** [comment]
Hi @jmml97, we are having a difficult time reproducing this issue. Is there by chance a sample project you could provide where this issue occurs?

**Comment by jmml97** [comment]
Oh, no @snehara99. I'm sorry but hte project where I'm having this problem is a work project and cannot share it. Is there any other type of information (logs, diagnostics) that I could possibly share?

**Comment by snehara99** [comment]
@jmml97 that's okay! Would you be able to share just `/app/build/CMakeCache.txt`? You can redact any sensitive information.

**Comment by jmml97** [comment]
@snehara99 Yes! Here it is [CMakeCache.txt](https://github.com/microsoft/vscode-cmake-tools/files/12036698/CMakeCache.txt)

**Comment by zs191025** [comment]
Hey, I encountered similar problem. Here is the error log in `Extension Host (Remote)` 

```text
2023-07-28 07:35:35.028 [error] SyntaxError: Unexpected token { in JSON at position 687
	at JSON.parse (<anonymous>)
	at CTestDriver.refreshTests (/root/.vscode-server/extensions/ms-vscode.cmake-tools-1.14.34/dist/main.js:38716:37)
	at async /root/.vscode-server/extensions/ms-vscode.cmake-tools-1.14.34/dist/main.js:35058:29
	at async CMakeProject.doConfigure (/root/.vscode-server/extensions/ms-vscode.cmake-tools-1.14.34/dist/main.js:35145:24) cmake.configure {"value":"ms-vscode.cmake-tools","_lower":"ms-vscode.cmake-tools"}
```

I inspect the `dist/main.js`:

```js
            const result = await driver.executeCommand(ctestpath, ['--show-only=json-v1', ...ctestArgs], undefined, { cwd: driver.binaryDir, silent: true }).result;
            if (result.retc !== 0) {
                // There was an error running CTest. Odd...
                log.error(localize('ctest.error', 'There was an error running ctest to determine available test executables')); // <-- THIS LINE: 38716
                return result.retc || -3;
            }
            this.tests = (_c = JSON.parse(result.stdout)) !== null && _c !== void 0 ? _c : undefined;
```

**Comment by zs191025** [comment]
I've found that was caused by ctest being too old.

My ctest is
```
ctest3 version 3.14.7

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

It doesn't support `--show-only=json-v1`.

**Comment by zs191025** [comment]
I think I've found the reason. Here is `.vscode/settings.json`

```
{
    "cmake.ctestArgs": [
        "-T",
        "memcheck"
    ]
}
```

This will cause ctest being invoked with args `--show-only=json-v1 -T test -T memcheck`. Then, ctest
will output two JSON snippets without any separator.

**Comment by snehara99** [comment]
Hi @zs191025, thank you for pointing this out! I will work on a repro using this information :)

**Comment by jmml97** [comment]
The problem seems to have gone away using a newer version of `ctest`.

**Comment by gcampbell-msft** [comment]
@jmml97 This is great! Thanks for the heads up. Since the issue is no longer appearing, I'll close the issue. Please either comment here or open a new issue if it arises again.
