### ISSUE TITLE
YAMLException: null byte is not allowed in input (1:9)

### ISSUE THREAD

**Issue by duklin** [microsoft/vscode-cmake-tools#3382]
### Brief Issue Summary

When I build a project from VS Code, the build is successful, but the following exception occurs:
```
[build] [ 96%] Linking CXX executable instant-ngp
[build] [ 97%] Built target instant-ngp
[build] [ 98%] Linking CXX shared library pyngp.cpython-39-x86_64-linux-gnu.so
[variant] Error parsing /home/duklin/repos/instant-ngp/instant-ngp: 
	YAMLException: null byte is not allowed in input (1:9)

 1 | ELF
-------------^
 2 | 
 3 | 
	at generateError (/home/duklin/.vscode-server/extensions/ms-vscode.cmake-tools-1.15.31/dist/main.js:21369:10)
	at throwError (/home/duklin/.vscode-server/extensions/ms-vscode.cmake-tools-1.15.31/dist/main.js:21373:9)
	at loadDocuments (/home/duklin/.vscode-server/extensions/ms-vscode.cmake-tools-1.15.31/dist/main.js:22862:5)
	at Object.load (/home/duklin/.vscode-server/extensions/ms-vscode.cmake-tools-1.15.31/dist/main.js:22900:19)
	at VariantManager._reloadVariantsFile (/home/duklin/.vscode-server/extensions/ms-vscode.cmake-tools-1.15.31/dist/main.js:55665:41)
[variant] Loaded new set of variants
[build] [100%] Built target pyngp
[build] [100%] Built target libopenxr_loader.so.1.0
[driver] Build completed: 00:01:14.037
[build] Build finished with exit code 0
```
Can you please explain why this exception happens?

### CMake Tools Diagnostics

```shell
{
  "os": "linux",
  "vscodeVersion": "1.77.3",
  "cmtVersion": "1.15.31",
  "configurations": [
    {
      "folder": "/home/duklin/repos/instant-ngp",
      "cmakeVersion": "3.26.4",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {
        "C": "/usr/bin/gcc",
        "CXX": "/usr/bin/g++"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 13,
    "executablesCount": 1,
    "librariesCount": 8,
    "targets": [
      {
        "name": "instant-ngp",
        "type": "EXECUTABLE"
      },
      {
        "name": "ngp",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "optix_program",
        "type": "OBJECT_LIBRARY"
      },
      {
        "name": "pyngp",
        "type": "SHARED_LIBRARY"
      },
      {
        "name": "tiny-cuda-nn",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "fmt",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "generate_openxr_header",
        "type": "UTILITY"
      },
      {
        "name": "libopenxr_loader.so.1.0",
        "type": "UTILITY"
      },
      {
        "name": "openxr_loader",
        "type": "SHARED_LIBRARY"
      },
      {
        "name": "uninstall",
        "type": "UTILITY"
      },
      {
        "name": "xr_global_generated_files",
        "type": "UTILITY"
      },
      {
        "name": "glfw",
        "type": "SHARED_LIBRARY"
      },
      {
        "name": "glfw_objects",
        "type": "OBJECT_LIBRARY"
      }
    ]
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

**Comment by gcampbell-msft** [comment]
@duklin Thanks for the issue, it's hard to know exactly what's going wrong in this example without a reproduction, is there an example repro project that you could share so that we can investigate this further? Thanks.

**Comment by duklin** [comment]
@gcampbell-msft thanks for the response. Here is a sample [repo](https://github.com/NVlabs/instant-ngp)
I get the exception with clang 10, but I do not get it when I use GCC 11. I have only tested `Debug` and `RelWithDebInfo` build variants, since those two are the ones I use.
