### ISSUE TITLE
doesn't start on remote 

### ISSUE THREAD

**Issue by Miktor** [microsoft/vscode-cmake-tools#739]
Cmake tools fails to start on remote.
Here is exception:
```
[Extension Host] Here is the error stack:  TypeError: Cannot read property 'length' of null
	at r._resolveLookupPaths (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/bootstrap.js:5:820)
	at Function.r._resolveLookupPaths (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/bootstrap.js:5:466)
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:574:20)
	at Function.Module._resolveFilename (/home/dmitrygladky/.vscode-server-insiders/extensions/vector-of-bool.cmake-tools-1.1.3/node_modules/module-alias/index.js:43:29)
	at Module._load (internal/modules/cjs/loader.js:507:25)
	at t._load (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/vs/server/remoteExtensionHostProcess.js:778:656)
	at y.load (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/vs/server/remoteExtensionHostProcess.js:679:325)
	at Function.n._load (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/vs/server/remoteExtensionHostProcess.js:744:390)
	at Function.i._load (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/vs/server/remoteExtensionHostProcess.js:735:925)
	at Module.require (internal/modules/cjs/loader.js:637:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Object.<anonymous> (/home/dmitrygladky/.vscode-server-insiders/extensions/vector-of-bool.cmake-tools-1.1.3/out/src/nag.js:13:14)
	at Module._compile (internal/modules/cjs/loader.js:689:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
	at Module.load (internal/modules/cjs/loader.js:599:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
	at Function.Module._load (internal/modules/cjs/loader.js:530:3)
	at Function.t._load (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/vs/server/remoteExtensionHostProcess.js:778:656)
	at Function.n._load (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/vs/server/remoteExtensionHostProcess.js:744:427)
	at Function.i._load (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/vs/server/remoteExtensionHostProcess.js:735:925)
	at Module.require (internal/modules/cjs/loader.js:637:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Object.<anonymous> (/home/dmitrygladky/.vscode-server-insiders/extensions/vector-of-bool.cmake-tools-1.1.3/out/src/cmake-tools.js:28:15)
	at Module._compile (internal/modules/cjs/loader.js:689:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
	at Module.load (internal/modules/cjs/loader.js:599:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
	at Function.Module._load (internal/modules/cjs/loader.js:530:3)
	at Function.t._load (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/vs/server/remoteExtensionHostProcess.js:778:656)
	at Function.n._load (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/vs/server/remoteExtensionHostProcess.js:744:427)
	at Function.i._load (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/vs/server/remoteExtensionHostProcess.js:735:925)
	at Module.require (internal/modules/cjs/loader.js:637:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Object.<anonymous> (/home/dmitrygladky/.vscode-server-insiders/extensions/vector-of-bool.cmake-tools-1.1.3/out/src/extension.js:14:23)
	at Module._compile (internal/modules/cjs/loader.js:689:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
	at Module.load (internal/modules/cjs/loader.js:599:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
	at Function.Module._load (internal/modules/cjs/loader.js:530:3)
	at Function.t._load (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/vs/server/remoteExtensionHostProcess.js:778:656)
	at Function.n._load (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/vs/server/remoteExtensionHostProcess.js:744:427)
	at Function.i._load (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/vs/server/remoteExtensionHostProcess.js:735:925)
	at Module.require (internal/modules/cjs/loader.js:637:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Function.i [as __$__nodeRequire] (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/vs/loader.js:32:381)
	at f._loadCommonJSModule (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/vs/server/remoteExtensionHostProcess.js:745:571)
	at f._doActivateExtension (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/vs/server/remoteExtensionHostProcess.js:649:27)
	at f._activateExtension (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/vs/server/remoteExtensionHostProcess.js:648:108)
	at f.<anonymous> (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/vs/server/remoteExtensionHostProcess.js:645:937)
	at Generator.next (<anonymous>)
	at /home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/vs/server/remoteExtensionHostProcess.js:13:979
	at new Promise (<anonymous>)
	at n (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/vs/server/remoteExtensionHostProcess.js:13:756)
	at Object.actualActivateExtension (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/vs/server/remoteExtensionHostProcess.js:645:639)
	at p._activateExtension (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/vs/server/remoteExtensionHostProcess.js:492:144)
	at r.length.Promise.all.s.map.e (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/vs/server/remoteExtensionHostProcess.js:491:814)
	at Array.map (<anonymous>)
	at p._activateExtensions (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/vs/server/remoteExtensionHostProcess.js:491:802)
	at p.activateById (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/vs/server/remoteExtensionHostProcess.js:489:864)
	at f._activateById (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/vs/server/remoteExtensionHostProcess.js:646:838)
	at f.<anonymous> (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/vs/server/remoteExtensionHostProcess.js:652:100)
	at Generator.next (<anonymous>)
	at o (/home/dmitrygladky/.vscode-server-insiders/bin/1c6e25b87e05a8429c986c59431be77467af9449/out/vs/server/remoteExtensionHostProcess.js:13:812)
```

Localy it's runs OK. And i've tried to reproduce this issue on stable build of vscode, but there is no repro.
I think the bug in the latest build of vscode-insiders because i've updated it lately, but not sure.

- **Host Operating System**:  macOS 10.14.6 (18G87)
- **CMake Version**: 3.12.1
- **VSCode Version**: 1.38.0-insider
- **CMake Tools Extension Version**: 1.1.13

**Comment by bobbrow** [comment]
Closing old issue. I haven't heard of any current issues with running our extension on a remote.
