### ISSUE TITLE
WSL: Launch gets stuck when externalConsole is true

### ISSUE THREAD

**Issue by fefrei** [microsoft/vscode-cmake-tools#749]
### Brief Issue Summary

I'm using CMake tools on Windows in conjunction with the WSL and C/C++ extensions. When using `launch.json` (because I need command line arguments), the launch gets stuck when `externalConsole` is `true`.

So, what happens is this:

1. I click ▷ next to my launch configuration in the debug bar.
2. The CMake build runs as it should, ending with `[build] Build finished with exit code 0`

Then, if `externalConsole` is off, after a few seconds, my program starts and runs normally. If it is on, nothing really happens anymore. My program is not started, and VS Code ends up looking like this:

![image](https://user-images.githubusercontent.com/3078885/63837016-f4194280-c97a-11e9-8bef-8fe7e810e82e.png)

### CMake Tools Log

For a failing start, the build output looks like this:

```
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /mnt/c/Users/felix/git/draisine-hypro/tool/build --config Debug --target saved-cli -- -j 4
[build] [100%] Built target saved-cli
[build] Build finished with exit code 0
```

### Developer Tools Log

Here's the developer console output for a failing run:

```
[Extension Host] [CMakeTools] 2019-08-28T08:04:26.210Z [debug] [extension] [1694] cmake.launchTargetPath started
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:26.211Z [debug] [extension] Start selection of kits. Found 7 kits.
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:26.211Z [debug] [extension] Opening kit selection QuickPick
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:28.811Z [debug] [extension] User selected kit  {"label":"[Unspecified]","description":"Unspecified (Let CMake guess what compilers and environment to use)","kit":{"name":"__unspec__"}}
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:28.812Z [debug] [rollbar] Updated Rollbar payload {"kit":{"name":"__unspec__"}}
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:28.814Z [debug] [main] Injecting new Kit into CMake driver
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:28.973Z [debug] [main] Starting new CMake driver
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:28.975Z [debug] [main] Starting CMake driver
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:28.979Z [debug] [driver] CMakeDriver Kit set to __unspec__
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:28.980Z [debug] [driver] Run _refreshExpansions
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:28.981Z [debug] [cms-driver] Run doRefreshExpansions
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:28.982Z [debug] [driver] Run _refreshExpansions cb
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:29.041Z [debug] [cms-client] Started new CMake Server instance with PID 5821
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:30.048Z [debug] [cache] Reading CMake cache file /mnt/c/Users/felix/git/draisine-hypro/tool/build/CMakeCache.txt
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:30.051Z [debug] [cache] Parsing CMake cache string
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:30.142Z [debug] [driver] Setting new variant , Emit debug information without performing optimizations
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:30.142Z [debug] [driver] Run _refreshExpansions
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:30.143Z [debug] [cms-driver] Run doRefreshExpansions
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:30.143Z [debug] [driver] Run _refreshExpansions cb
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:30.199Z [debug] [cms-client] Started new CMake Server instance with PID 5822
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:31.202Z [debug] [cache] Reading CMake cache file /mnt/c/Users/felix/git/draisine-hypro/tool/build/CMakeCache.txt
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:31.204Z [debug] [cache] Parsing CMake cache string
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:31.318Z [debug] [main] Run configure  
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:31.319Z [debug] [main] Saving open files before configure/build
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:31.584Z [debug] [driver] Start configure  
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:31.585Z [debug] [driver] Runnnig pre-configure checks and steps
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:31.588Z [debug] [driver] Run _refreshExpansions
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:31.589Z [debug] [cms-driver] Run doRefreshExpansions
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:31.589Z [debug] [driver] Run _refreshExpansions cb
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:31.879Z [info] [cmake] Found HyPro.
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:31.901Z [info] [cmake] Found Carl.
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:31.910Z [info] [cmake] Carl include dir: /mnt/c/Users/felix/git/carl/src
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:31.911Z [info] [cmake] Carl include dirs: 
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:31.912Z [info] [cmake] Carl libraries: carl-shared
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:31.913Z [info] [cmake] Carl lib: 
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:31.946Z [info] [cmake] Configuring done
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:32.975Z [info] [cmake] Generating done
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:33.561Z [debug] [cache] Reading CMake cache file /mnt/c/Users/felix/git/draisine-hypro/tool/build/CMakeCache.txt
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:33.570Z [debug] [cache] Parsing CMake cache string
console.ts:137 [Extension Host] updateCustomBrowseConfiguration
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:40.098Z [debug] [cache] Reading CMake cache file /mnt/c/Users/felix/git/draisine-hypro/tool/build/CMakeCache.txt
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:40.104Z [debug] [cache] Parsing CMake cache string
console.ts:137 [Extension Host] updateCustomBrowseConfiguration
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:40.382Z [debug] [main] Run build saved-cli
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:40.522Z [debug] [main] Saving open files before configure/build
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:40.661Z [info] [build] Starting build
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:40.704Z [debug] [driver] Start build saved-cli
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:40.705Z [debug] [driver] Runnnig pre-configure checks and steps
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:40.711Z [info] [proc] Executing command: /usr/bin/cmake --build /mnt/c/Users/felix/git/draisine-hypro/tool/build --config Debug --target saved-cli -- -j 4
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:51.864Z [info] [build] [100%] Built target saved-cli
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:52.060Z [debug] [driver] Run _refreshExpansions
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:52.061Z [debug] [cms-driver] Run doRefreshExpansions
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:52.062Z [debug] [driver] Run _refreshExpansions cb
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:52.124Z [info] [build] Build finished with exit code 0
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:52.184Z [debug] [extension] [1694] cmake.launchTargetPath finished (returned "/mnt/c/Users/felix/git/draisine-hypro/tool/build/bin/saved-cli")
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:52.289Z [debug] [cache] Reading CMake cache file /mnt/c/Users/felix/git/draisine-hypro/tool/build/CMakeCache.txt
console.ts:137 [Extension Host] [CMakeTools] 2019-08-28T08:04:52.299Z [debug] [cache] Parsing CMake cache string
console.ts:137 [Extension Host] updateCustomBrowseConfiguration
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: can't find terminal application 'xterm'
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:38
_doInvokeHandler @ rpcProtocol.ts:394
_invokeHandler @ rpcProtocol.ts:379
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:572
a @ ipc.net.ts:421
e @ ipc.net.ts:428
fire @ event.ts:572
_receiveMessage @ ipc.net.ts:715
S._socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:578
fire @ event.ts:572
acceptChunk @ ipc.net.ts:236
_register._socket.onData.e @ ipc.net.ts:197
t @ ipc.net.ts:28
emit @ events.js:182
addChunk @ _stream_readable.js:283
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onStreamRead @ internal/stream_base_commons.js:94
console.ts:137 [Extension Host] stack trace: Error: can't find terminal application 'xterm'	at v (/home/fefrei/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:396:76)	at ChildProcess.g.on.e (/home/fefrei/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:399:678)	at ChildProcess.emit (events.js:182:13)	at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)	at onErrorNT (internal/child_process.js:407:16)	at process._tickCallback (internal/process/next_tick.js:63:19)
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:38
_doInvokeHandler @ rpcProtocol.ts:394
_invokeHandler @ rpcProtocol.ts:379
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:572
a @ ipc.net.ts:421
e @ ipc.net.ts:428
fire @ event.ts:572
_receiveMessage @ ipc.net.ts:715
S._socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:578
fire @ event.ts:572
acceptChunk @ ipc.net.ts:236
_register._socket.onData.e @ ipc.net.ts:197
t @ ipc.net.ts:28
emit @ events.js:182
addChunk @ _stream_readable.js:283
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onStreamRead @ internal/stream_base_commons.js:94
log.ts:173   ERR can't find terminal application 'xterm': Error: can't find terminal application 'xterm'
	at v (/home/fefrei/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:396:76)
	at ChildProcess.g.on.e (/home/fefrei/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:399:678)
	at ChildProcess.emit (events.js:182:13)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
	at onErrorNT (internal/child_process.js:407:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)
```
The complaint about the missing `xterm` is probably the most relevant line – but even if this is the root cause, I think this should be reported properly instead of stalling.

### Platform and Versions

- **Operating System**: Windows 10
- **CMake Version**: `3.10.2`
- **VSCode Version**: `1.37.1`
- **CMake Tools Extension Version**: `1.1.3`
- **Compiler/Toolchain**: Unspecified kit, which should end up using `g++-8`

**Comment by bobbrow** [comment]
I can reproduce the problem, but this doesn't appear to be related to the CMake Tools extension.  `externalConsole` is a VS Code feature.  I would recommend reporting this to them.

As an FYI, you can avoid using tasks.json if you set the debug parameters you want in the `cmake.debugConfig` setting:
![image](https://user-images.githubusercontent.com/12818240/63964100-3ca03100-ca4b-11e9-9bed-862061e3e60c.png)
